#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""cosmetic-derm 第5批：meso-cocktail / mesotherapy / microneedle / pifuphceding"""
import os, re, json, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = os.path.join(ROOT, '_en-i18n', 'work', 'cosmetic-derm')
OUT = os.path.join(ROOT, 'i18n', 'tools', 'en', 'cosmetic-derm')

CJK = re.compile(r'[\u4e00-\u9fff]')
CNP = re.compile(r'[，。、；：！？（）「」『』]')

EXTRA = {}


def build(slug, en_list):
    wj = json.load(open(os.path.join(WORK, slug + '.json'), encoding='utf-8'))
    items = wj.get('items', [])
    if len(en_list) != len(items):
        print('LEN MISMATCH', slug, len(en_list), len(items))
        for i, it in enumerate(items):
            print('   ', i, repr((it.get('zh') or it.get('zh_src', ''))[:50]))
        sys.exit(1)
    mp = {}
    for it, en in zip(items, en_list):
        if it.get('src_diff') and it.get('zh_src') and 'related-tool' not in it.get('loc', ''):
            z = it['zh_src'].strip()
        else:
            z = it.get('zh', '').strip()
        if CJK.search(en) or CNP.search(en):
            print('BAD EN', slug, repr(z), repr(en))
            sys.exit(1)
        mp[z] = en
    for z, en in EXTRA.get(slug, {}).items():
        if CJK.search(en) or CNP.search(en):
            print('BAD EXTRA', slug, repr(z), repr(en))
            sys.exit(1)
        mp[z] = en
    return mp


def write(slug, mp):
    wj = json.load(open(os.path.join(WORK, slug + '.json'), encoding='utf-8'))
    name = wj.get('exist_en') or wj.get('name') or slug
    out = {'slug': slug, 'industry': 'cosmetic-derm', 'name': name, 'map': mp}
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, slug + '.json'), 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
        f.write('\n')
    print('WROTE', slug, '(+%d)' % len(mp))


# ---------------- meso-cocktail (55) ----------------
write('meso-cocktail', build('meso-cocktail', [
    "\u2728 Mesotherapy (Cocktail) Formula Builder",
    "Select treatment goals by skin concern to auto-generate a mesotherapy cocktail formula, concentration and injection parameters.",
    "Mesotherapy Formula Builder",
    "/ Mesotherapy Formula Builder",
    '\U0001F4D6 View the "Mesotherapy (Cocktail) Formula Builder User Guide"',
    "Treatment goals (multi-select)",
    "Hydration",
    "Brightening / spot fading",
    "Anti-aging",
    "Barrier repair",
    "Oil control / anti-acne",
    "Hair-loss treatment",
    "Total formula volume (ml)",
    "Treatment frequency",
    "Once weekly (intensive phase)",
    "Every 2 weeks (standard)",
    "Monthly (maintenance phase)",
    "Patient sensitivity",
    "Sensitive (lower concentration)",
    "Tolerant (can raise concentration)",
    "Treatment sessions",
    "3rd session",
    "5th session",
    "Generate formula",
    "\U0001F4CB Mesotherapy Common Ingredient Library",
    "Core efficacy",
    "Moisturizing",
    "Dermal hydration",
    "Brightening",
    "Melanin inhibition",
    "Antioxidant / detox",
    "Anti-aging",
    "Firming / lifting",
    "Organic silicon",
    "Collagen synthesis",
    "Growth factors",
    "Tissue regeneration",
    "Vitamin B complex",
    "Oil control",
    "Sebum regulation",
    "\u26A0\uFE0F Mesotherapy formulas must be individualized; the formula generated by this tool is for licensed physicians' reference only. Perform an allergy test before actual use and mind incompatibility between ingredients.",
    "\U0001F4DA Deep Dive: Mesotherapy (Cocktail) Formula Builder",
    "Plan demo: show the physician the ingredient ratios you want to combine, easing professional review and adjustment.",
    "Ratio check: when preparing multiple doses, scale linearly by total volume to avoid ratio drift.",
    "Contraindication alert: recognize the risk of combinations where some ingredients should not be mixed in one vial.",
    "Brightening cocktail ratio",
    "Input: HA 1% + VC 2% + trace peptides, total 5 mL \u2192 outputs each stock volume and base-liquid ratio, with a note to prepare away from light and use fresh.",
    "Are more ingredients better?",
    "No. More types raise incompatibility and irritation risk; keep it few and refined, and follow professional advice.",
    "Can I inject at home myself?",
    "No. Mesodermal injection is a medical act; self-operation carries infection and embolism risk.",
    "Can the result serve as a prescription?",
    "No. It is only a ratio calculation; the prescription is written by a physician.",
    'About "Mesotherapy Formula Builder"',
    "Mesotherapy (cocktail) formula builder: online generates a mesotherapy cocktail formula and concentration ratio by skin concern. A medical professional tool based on authoritative medical standards; for reference only.",
]))

# ---------------- mesotherapy (53) ----------------
write('mesotherapy', build('mesotherapy', [
    "\U0001F9B4 Hydration Injection (Ingredient / Volume) Ratio Calculator",
    "Based on skin concerns and treatment goals, calculate each hydration-injection ingredient's ratio, concentration and total volume.",
    "Hydration Injection Ratio Calculator",
    "/ Hydration Injection Ratio Calculator",
    '\U0001F4D6 View the "Hydration Injection (Ingredient / Volume) Ratio Calculator User Guide"',
    "Each ingredient volume = total \u00d7 ingredient ratio; content = volume \u00d7 reference concentration; saline fills the remainder",
    "Ratio logic: non-cross-linked hyaluronic acid as base (50%, or 30% if PRP is included); PRP 30%, vitamin C 10%, peptides / growth factors 5% (0.5%), micro-botulinum 2% (~5 U/ml, \u226430 U full face), PDRN 15% (cap 2 ml), glutathione 3% (600 mg/4 ml). Saline = total \u2212 sum of ingredient volumes, used to top up the total (counted when >0.1 ml). At least HA or PRP must be chosen as a base. Used for hydration-injection formula ingredient and dosage accounting.",
    "Total mix volume (ml)",
    "Injection layer",
    "Superficial (papillary dermis 1\u20131.5 mm)",
    "Mid (reticular dermis 1.5\u20132 mm)",
    "Deep (subcutaneous 2\u20132.5 mm)",
    "Syringe size",
    "1 ml syringe",
    "2 ml syringe",
    "3 ml syringe",
    "5 ml syringe",
    "Ingredient selection and ratio",
    "Non-cross-linked HA (base hydration)",
    "Vitamin C (brightening antioxidant)",
    "Autologous PRP (repair / regeneration)",
    "Peptides / growth factors (anti-aging repair)",
    "Micro-botulinum (oil control / pore tightening)",
    "PDRN (salmon DNA extract)",
    "Glutathione (brightening)",
    "\U0001F4CB Hydration Injection Common Ingredient Reference",
    "Main efficacy",
    "Non-cross-linked HA",
    "Hydration, water binding",
    "Brightening, antioxidant",
    "Repair, collagen regeneration",
    "Peptides",
    "Anti-aging, repair",
    "Micro-botulinum",
    "Oil control, pore tightening",
    "Tissue repair / regeneration",
    "Brightening, detox",
    "\u26A0\uFE0F Hydration injection is a medical act; ingredient ratio and concentration must be set by a physician per individual. Improper mixing may cause adverse reactions or reduce potency.",
    "\U0001F4DA Deep Dive: Hydration Injection (Ingredient / Volume) Ratio Calculator",
    "Consult communication: translate 'how many ml, how much HA' into quantifiable metrics for easier price comparison.",
    "Zoning plan: allocate injection volume by forehead / cheek / jaw to avoid local over-dose.",
    "Repurchase log: record total HA each time and observe long-term hydration-improvement trend.",
    "Single-session hydration HA total",
    "Input: 2% HA total 3 mL \u2192 effective HA about 60 mg, zoning about 1 mL per cheek, with a note for clinic to prepare fresh with aseptic technique.",
    "Does more volume mean more hydrated?",
    "No. The single-session total has a safety window; excess raises swelling and nodule risk.",
    "Can I do hydration injection at home?",
    "No. It is a medical injection with infection and vascular-embolism risk; it must be done in a clinic.",
    "Can this result serve as a basis?",
    "No. It is only arithmetic conversion; the actual plan is set by a physician.",
    'About "Hydration Injection Ratio Calculator"',
    "Hydration injection (ingredient / volume) ratio calculator: compute each ingredient's ratio and injection concentration online. A medical professional tool based on authoritative medical standards; for reference only.",
    "Full face approx. 300 cm\u00b2",
]))

# ---------------- microneedle (43) ----------------
write('microneedle', build('microneedle', [
    "\U0001F9EE Microneedle (Length / Spacing) Penetration Calculator",
    "Based on microneedle length, spacing, density and passes, calculate penetration depth and active-ingredient delivery amount.",
    "Microneedle Penetration Calculator",
    "/ Microneedle Penetration Calculator",
    '\U0001F4D6 View the "Microneedle (Length / Spacing) Penetration Calculator User Guide"',
    "Micropore density = (1 / spacing_mm\u00b2) \u00d7 100 pores/cm\u00b2; single-pore volume = \u03c0 r\u00b2 h / 3 (cone); effective delivery = total pore volume \u00d7 molecular-weight factor \u00d7 concentration / 100",
    "Effective depth = needle length \u00d7 0.75 (skin-recoil discount); single-pore radius r = diameter \u03bcm \u00f7 2 \u00f7 1000 (mm); total pore volume = density \u00d7 area \u00d7 single-pore volume \u00d7 passes (mm\u00b3 \u2248 \u03bcL). Molecular-weight factor: <1 kDa 0.95, <10 kDa 0.85, <100 kDa 0.65, <500 kDa 0.45, otherwise 0.30. Single-pass delivery = effective volume \u00d7 concentration/100 (1% of 1 \u03bcL \u2248 10 \u03bcg). Used for transdermal microneedle flux and dosage estimation of drugs / active ingredients.",
    "Microneedle length (mm)",
    "Needle spacing (mm)",
    "Needle diameter (\u03bcm)",
    "Passes",
    "Drug delivery (active-ingredient infusion)",
    "Collagen induction (scar / wrinkle improvement)",
    "Hair-loss treatment (scalp infusion)",
    "Infused ingredient molecular weight (Da)",
    "Applied concentration (%)",
    "\U0001F4CB Microneedle Length and Indications",
    "Length",
    "Layer reached",
    "Daily infusion, skin-texture improvement",
    "Superficial dermis",
    "Pigmentation, mild wrinkles",
    "Mid dermis",
    "Wrinkles, enlarged pores, shallow scars",
    "Atrophic scars, stretch marks",
    "Subcutaneous layer",
    "Deep scars, hair-loss treatment",
    "\u26A0\uFE0F Microneedle length >1.0 mm is a medical procedure, performed by a physician. Improper operation may cause infection, scarring or pigmentation. Strict aseptic technique.",
    "\U0001F4DA Deep Dive: Microneedle (Length / Spacing) Penetration Calculator",
    "Needle-choice education: compare penetration depth and scenarios for 0.25 / 0.5 / 1.0 mm.",
    "Operation planning: estimate needle density by treatment area size to avoid excessive overlap.",
    "Recovery forecast: longer needles mean a longer redness period; schedule a rest day.",
    "1.0 mm home-use assessment",
    "Input: needle length 1.0 mm, spacing 1.5 mm \u2192 enters near the mesoderm; bleeding risk rises, suggest a clinic or professional guidance.",
    "What is the longest length for home use?",
    "Most advise not exceeding 0.5 mm for penetration boosting; longer should be done by a professional.",
    "Need sun protection after microneedling?",
    "Yes. During the open-channel period pigmentation is easier; strict sun protection and repair.",
    "Can this calculation set the plan?",
    "No. It is only a parameter illustration; defer actual operation to professionals.",
    'About "Microneedle Penetration Calculator"',
    "Microneedle (length / spacing) penetration calculator: compute the optimal length, spacing and drug penetration for microneedle treatment online. A medical professional tool based on authoritative medical standards; for reference only.",
    "Hyaluronic acid approx. 50 kDa",
]))

# ---------------- pifuphceding (35) ----------------
write('pifuphceding', build('pifuphceding', [
    "\U0001F9B4 Skin pH Measurement",
    "Enter the skin pH to judge the acid-base state and barrier health.",
    '\U0001F4D6 View the "Skin pH Measurement User Guide"',
    "Skin-surface pH grading: <4.0 strongly acidic, 4.0\u20134.5 mildly acidic, 4.5\u20135.5 normal weakly acidic, 5.5\u20136.5 mildly alkaline, >6.5 alkaline; deviation from normal suggests impaired skin barrier.",
    "Skin pH value",
    "Forehead (T-zone)",
    "\U0001F4A1 The normal skin-surface pH range is 4.5\u20135.5 (weakly acidic), the skin barrier's 'acid mantle' protective layer.",
    "Press",
    "quick judge,",
    "Copy result",
    "pH must be measured with a skin pH meter or test paper; results are for reference only.",
    "\U0001F559 Latest judgment",
    "No judgment records yet",
    "\U0001F4DA Deep Dive: Skin pH Measurement",
    "Barrier monitoring: a high pH often accompanies barrier damage or over-cleansing, suggesting adjusting the cleanser.",
    "Product choice: for alkaline-leaning skin avoid soap bases; choose a weakly acidic mild cleanser.",
    "Education: explain that 'cleaner and more alkaline is not better for skin'.",
    "Post-cleansing high pH",
    "Input: measured pH 6.8 \u2192 mildly alkaline, suggesting over-strong cleansing or insufficient rinsing; suggest switching to an amino-acid cleanser and rinsing with warm water.",
    "What pH counts as normal?",
    "The facial surface is usually 4.5\u20135.5 weakly acidic, with individual differences.",
    "Are home test strips accurate?",
    "Reference-grade. Affected by sweat and skincare residue; cleanse and wait 30 minutes before measuring for stability.",
    "Does mildly alkaline matter?",
    "No harm short-term; chronically high is bad for the barrier\u2014just adjust care; see a doctor if discomfort persists.",
    'About "Skin pH Measurement"',
    "Skin pH measurement tool: judge the skin's acid-base state and barrier health from the measured pH, and give skincare adjustment advice.",
    "Acid-base state judgment",
    "Barrier health score",
    "pH scale visualization",
    "Skincare adjustment advice",
    "Skin barrier assessment",
    "Cleanser selection",
    "Skincare plan adjustment",
    "Skin pH value",
]))
