#!/usr/bin/env python3
"""Q1 候选缺口扫描：扫描 tools.json，挑出确实缺失的高价值工具方向。
用法：python3 scripts/_q1_gap_scan.py
输出 ABSENT 列表（子串在全站 name/desc/en/ed 中均未出现）。
"""
import json, re, sys

PATH = "json/tools.json"
# 候选主题词 -> 检测子串（小写）。缺失=潜在缺口。
CANDIDATES = {
    "渐变生成器": "gradient",
    "box-shadow 生成": "box-shadow",
    "flexbox 生成": "flexbox",
    "圆角生成": "border-radius",
    "调色板生成": "palette",
    "SVG 优化": "svg optim",
    "favicon 生成": "favicon",
    "meta 标签生成": "meta tag",
    "open graph": "open graph",
    "latex": "latex",
    "markdown 预览": "markdown preview",
    "toml": "toml",
    "ini 编辑": "ini ",
    "正则测试器": "regex tester",
    "csv 转 json": "csv to json",
    "xml 格式化": "xml format",
    "分数计算器": "fraction",
    "小费计算器": "tip calculat",
    "复利计算": "compound",
    "折旧计算": "折旧",
    "摊销计算": "摊销",
    "基金定投": "定投",
    "养老金": "养老",
    "油耗计算": "油耗",
    "运费计算": "运费",
    "混凝土用量": "混凝土",
    "瓷砖用量": "瓷砖",
    "地板用量": "地板",
    "屋顶": "屋顶",
    "太阳能": "太阳能",
    "电池续航": "电池",
    "空调负荷": "空调",
    "保温": "保温",
    "床垫": "床垫",
    "枕头": "枕头",
    "厨房": "厨房",
    "营养": "营养",
    "睡眠": "睡眠",
    "步数": "步数",
    "心率": "心率",
    "血压": "血压",
    "血糖": "血糖",
    "行李": "行李",
    "时区": "时区",
    "年龄计算": "年龄计算",
    "星座": "星座",
    "条形码": "条形码",
    "水印": "水印",
    "图片压缩": "图片压缩",
    "图片裁剪": "图片裁剪",
    "pdf 压缩": "pdf 压缩",
    "pdf 合并": "pdf 合并",
    "字幕": "字幕",
    "gif": "gif",
    "字符画": "字符画",
    "骰子": "骰子",
    "扑克": "扑克",
    "彩票": "彩票",
    "随机数": "随机数",
    "赔率": "赔率",
    "八进制": "八进制",
    "盲文": "盲文",
    "凯撒密码": "凯撒",
    "url 编码": "url 编码",
    "html 实体": "html 实体",
    "user agent": "user agent",
    "mime": "mime",
    "罗马数字": "罗马数字",
    "进制转换": "进制转换",
    "文本对比": "文本对比",
    "base64 文件": "base64 文件",
    "色盲模拟": "色盲",
    "对比度(已有)": "对比度",
    "emoji": "emoji",
    "二维码(已有)": "二维码",
    "barcode 已有": "barcode",
    # 第二轮：网络/转换/dev 工具
    "json 格式化": "json format",
    "json 校验": "json valid",
    "json 比对": "json diff",
    "yaml 转 json": "yaml to json",
    "toml 转": "toml to",
    "csv 转 yaml": "csv to yaml",
    "url 解码": "url 解码",
    "html 压缩": "html minif",
    "css 压缩": "css minif",
    "js 压缩": "js minif",
    "json 压缩": "json minif",
    "sql 格式化": "sql format",
    "密码强度": "密码强度",
    "iban": "iban",
    "bin 查询": "bin 查询",
    "mac 地址": "mac 地址",
    "子网": "子网",
    "ipv4": "ipv4",
    "http 状态码": "http 状态",
    "http 头": "http 头",
    "unicode 表": "unicode",
    "ascii 表": "ascii",
    "hmac": "hmac",
    "aes": "aes ",
    "rsa": "rsa",
    "whois": "whois",
    "dns 查询": "dns 查询",
    "端口": "端口",
    "证书": "证书",
    "token": "token",
    "oauth": "oauth",
    "字符编码": "字符编码",
    "emoji 搜索": "emoji 搜索",
    "字体内嵌": "字体内嵌",
    "字体预览": "字体预览",
    "px 转 rem": "px to rem",
    "rem 转 px": "rem to px",
    "vh vw": "vh",
    "黄金比例": "黄金比例",
    "斐波那契": "斐波那契",
    "随机数生成器": "随机数生成器",
    "洗牌": "洗牌",
    "抽签": "抽签",
    "转盘": "转盘",
    "倒计时": "倒计时",
    "正计时": "正计时",
    "秒表": "秒表",
    "日历": "日历",
    "农历": "农历",
    "节气": "节气",
    "汇率(已有)": "汇率",
    "复利(已有)": "复利",
    "个税(已有)": "个税",
    "房贷(已有)": "房贷",
    # 第三轮：it-tools 竞品缺口
    "ulid": "ulid",
    "yaml 转 json": "yaml to json",
    "yaml 转 toml": "yaml to toml",
    "json 转 toml": "json to toml",
    "list 转换": "list converter",
    "toml 转 json": "toml to json",
    "toml 转 yaml": "toml to yaml",
    "xml 转 json": "xml to json",
    "json 转 xml": "json to xml",
    "url 编码": "url encode",
    "ua 解析": "user-agent parser",
    "json 比对": "json diff",
    "json 压缩": "json minify",
    "浏览器信息": "device information",
    "basic auth": "basic auth",
    "otp": "otp",
    "keycode": "keycode",
    "slugify": "slugify",
    "wifi": "wifi qr",
    "svg 占位": "svg placeholder",
    "git 速查": "git cheatsheet",
    "随机端口": "random port",
    "chmod": "chmod",
    "子网": "subnet",
    "mac 地址生成": "mac address generator",
    "ipv6": "ipv6",
    "eta": "eta calculat",
    "emoji 选择": "emoji picker",
    "numeronym": "numeronym",
    "电话解析": "phone parser",
    "nato": "nato",
    "bip39": "bip39",
    "aes 加密": "encrypt text",
    "字符串混淆": "obfuscator",
    "文本转 ascii": "ascii binary",
}

def main():
    with open(PATH, encoding="utf-8") as f:
        tools = json.load(f)
    corpus = []
    for t in tools:
        s = " ".join([t.get("name",""), t.get("desc",""), t.get("en",""), t.get("ed","")]).lower()
        corpus.append(s)
    full = "\n".join(corpus)
    present, absent = [], []
    for label, tok in CANDIDATES.items():
        if tok.lower() in full:
            present.append((label, tok))
        else:
            absent.append((label, tok))
    print(f"工具总数: {len(tools)}")
    print(f"\n=== ABSENT（缺失，潜在候选 {len(absent)}）===")
    for label, tok in absent:
        print(f"  - {label}  [{tok}]")
    print(f"\n=== PRESENT（已存在，跳过 {len(present)}）===")
    for label, tok in present:
        print(f"  - {label}  [{tok}]")

if __name__ == "__main__":
    main()
