# -*- coding: utf-8 -*-
"""P3b 通用脚本：给 C 级计算类工具页就地注入 formula-box（计算公式面板），使其升为 A 级。

用法：
  python3 scripts/inject_formula_box.py --industry signal --map '{"slug":"公式"}'
  （也可在 MAPPINGS 字典里按行业预置，直接 python3 scripts/inject_formula_box.py --industry signal）

规则：
- 仅注入：若页面已含 formula-box 则跳过（幂等）。
- 插入位置：<h2> 之后的 intro <p> 之后（参照 materials/vickers-hardness 结构）。
- formula-eq：调用方提供（基于工具真实计算逻辑的标准公式）。
- formula-desc：自动取页面 intro 文本（html.escape 防注入）。
- 不改动文件名/URL/计算逻辑，零死链风险。
"""
import os, re, sys, json, html, argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS_DIR = os.path.join(ROOT, "tools")


def inject(industry, slug, eq):
    fp = os.path.join(TOOLS_DIR, industry, slug + ".html")
    if not os.path.exists(fp):
        return "missing"
    c = open(fp, encoding="utf-8").read()
    if "formula-box" in c:
        return "skip"
    # 提取 intro（h2 后那个特定 style 的 <p>）
    m = re.search(
        r'(<p style="font-size:13px;color:var\(--text-muted\);margin-bottom:\d+px;">.*?</p>)',
        c, re.S)
    if not m:
        return "no-intro"
    intro = re.sub(r"<[^>]+>", "", m.group(1)).strip()
    fb = (
        '\n    <div class="formula-box">\n'
        '      <div class="formula-title">📐 计算公式</div>\n'
        '      <div class="formula-eq">%s</div>\n'
        '      <p class="formula-desc">%s</p>\n'
        '    </div>' % (eq, html.escape(intro))
    )
    c2 = c[:m.end()] + fb + c[m.end():]
    open(fp, "w", encoding="utf-8").write(c2)
    return "ok"


# 各行业预置公式映射（slug -> formula-eq）。逐步扩充。
MAPPINGS = {
    "signal": {
        "natural-frequency-2nd": "ω_n = √(k/m)",
        "signal-power": "P = V_rms² / R",
        "snr-db": "SNR = 10·log₁₀(P_s / P_n)",
        "db-power-ratio": "dB = 10·log₁₀(P₁ / P₂)",
        "duty-cycle": "D = t_on / T × 100%",
        "q-factor": "Q = f₀ / Δf",
        "bit-rate-nyquist": "R_max = 2·B·log₂(M)",
        "nyquist-rate": "f_s ≥ 2·f_max",
        "db-voltage-ratio": "dB = 20·log₁₀(V₁ / V₂)",
        "energy-discrete": "E = Σ|x[n]|²",
        "group-delay": "τ_g = Δφ / Δω",
        "mod-index-am": "m = A_m / A_c",
        "mod-index-fm": "β = Δf / f_m",
        "bandwidth-q": "BW = f₀ / Q",
        "carrier-freq": "f_c = (f_H + f_L) / 2",
    },
    "quantum": {
        "fermi-energy-3d": "E_F = ħ²/(2m)·(3π²n)^{2/3}",
        "photon-flux": "N = P·λ/(h·c)",
        "photoelectric-threshold": "f₀ = φ/h",
        "zeeman-splitting": "ΔE = μ_B·B",
        "band-gap-photon": "λ = h·c/E_g",
        "compton-wavelength": "λ_c = h/(m·c)",
        "hydrogen-energy-level": "E_n = −13.6 eV / n²",
        "wavelength-frequency": "λ = c/f",
        "thermal-de-broglie": "λ = h/√(2π·m·k_B·T)",
        "boltzmann-population": "N₂/N₁ = e^(−ΔE/(k_B·T))",
        "spin-magnetic-moment": "μ = μ_B·m_l",
        "energy-time-uncertainty": "ΔE·Δt ≥ ħ/2",
        "angular-momentum-quant": "L = n·ħ",
        "quantum-oscillator-energy": "E_n = (n+½)·h·f",
        "stefan-boltzmann-power": "P = σ·A·T⁴",
    },
    "metrology": {
        "std-dev-type-a": "u_A = s/√n",
        "guard-band-95": "GB = 1.65·U",
        "least-count-error": "极限误差 = ±(分度值/2)",
        "ndc-number": "NDC = 1.41·PV/GRR",
        "combined-uncertainty": "u_c = √(Σu_i²)",
        "roundness-deviation": "圆度 = R_max − R_min",
        "flatness-deviation": "平面度 = 最高点 − 最低点",
        "calibration-uncertainty": "u_c = √(u_std² + u_rep²)",
        "relative-uncertainty": "u_r = u/|x| × 100%",
        "bias-percent": "偏倚% = (x − x_ref)/x_ref × 100%",
        "precision-tolerance-ratio": "PTR = 6·s/Tol",
        "bias-absolute": "偏倚 = x − x_ref",
        "gauge-reproducibility": "再现性 = R̄/d₂*",
        "grr-percent": "%GRR = GRR/Tol × 100%",
        "gauge-repeatability": "重复性 = R̄/d₂",
    },
    "aerospace": {
        "dynamic-pressure": "q = ½·ρ·v²",
        "lift-to-drag-ratio": "L/D = C_L/C_D",
        "centripetal-accel": "a = v²/r",
        "orbital-velocity": "v = √(μ/r)",
        "bank-angle-load": "n = 1/cos(φ)",
        "aspect-ratio": "AR = b²/S",
        "thrust-to-weight": "推重比 = T/W",
        "wing-loading": "翼载荷 = W/S",
        "wing-area-from-loading": "S = W/WL",
        "orbital-period": "T = 2π·√(r³/μ)",
        "payload-fraction": "有效载荷占比 = (m₀−m_f)/m₀ × 100%",
        "escape-velocity": "v_e = √(2μ/r)",
        "stats-weight-luggage": "均值 = Σx_i/n；标准差 s = √(Σ(x_i−x̄)²/(n−1))",
        "calc-gravity": "重心 X = Σ(W_i·x_i)/ΣW_i",
        "lift-force-attack-angle": "C_L ≈ C_L₀ + a·α",
    },
    "kinematics": {
        "relative-velocity-1d": "v_r = v₁ − v₂",
        "tangential-accel": "a_t = α·r",
        "tangential-velocity": "v_t = ω·r",
        "stopping-time": "t = v₀/a",
        "uniform-displacement": "s = v·t",
        "period-from-omega": "T = 2π/ω",
        "projectile-velocity-components": "v_x = v·cosθ, v_y = v·sinθ",
        "height-fall-distance": "h = ½·g·t²",
        "free-fall-time": "t = √(2h/g)",
        "rpm-to-radps": "ω = 2π·n/60",
        "freq-from-omega": "f = ω/(2π)",
    },
    "nuclear": {
        "dose-equivalent": "H = D·Q",
        "half-life-from-lambda": "T_{1/2} = ln2/λ",
        "nuclear-radius": "R = r₀·A^{1/3}, r₀≈1.2 fm",
        "absorbed-dose": "D = E/m",
        "effective-halflife": "1/T_e = 1/T_p + 1/T_b",
        "survival-probability": "P = e^(−λt)",
        "specific-activity-from-halflife": "a = (ln2/T_{1/2})·N_A/M",
        "activity-from-halflife": "A = (ln2/T_{1/2})·N",
        "mean-life-from-halflife": "τ = T_{1/2}/ln2",
        "decay-constant-from-halflife": "λ = ln2/T_{1/2}",
        "half-life-from-activity-nuclei": "T_{1/2} = N·ln2/A",
        "decay-fraction": "已衰变份额 = 1 − e^(−λt)",
    },
    "optics": {
        "f-number": "N = f/D",
        "magnification-optics": "M = −d_i/d_o",
        "resolving-power": "R = D/(1.22·λ)",
        "angular-magnification": "M = N/f",
        "telescope-magnification": "M = f_o/f_e",
        "prism-deviation": "δ = (n−1)·A",
        "focal-length-mirror": "f = R/2",
        "optical-power-diopter": "P = 1/f",
        "malus-law": "I = I₀·cos²θ",
    },
    "optical": {
        "f-number": "N = f/D",
        "optical-path-length": "OP = n·L",
        "critical-angle": "θ_c = arcsin(n₂/n₁)",
        "lens-power-diopter": "P = 1/f",
        "numerical-aperture": "NA = n·sinθ",
        "telescope-magnification": "M = f_o/f_e",
        "rayleigh-resolution": "θ = 1.22·λ/D",
    },
    "structural": {
        "shear-modulus": "G = E/(2(1+ν))",
        "radius-of-gyration": "r = √(I/A)",
        "moment-of-inertia-circle": "I = π·d⁴/64",
        "section-modulus-circle": "S = π·d³/32",
        "polar-moment-circle": "J = π·d⁴/32",
        "torsional-shear-shaft": "τ = T·(d/2)/J",
        "thermal-strain": "ε = α·ΔT",
        "axial-stress": "σ = F/A",
        "axial-strain": "ε = ΔL/L",
    },
    "geometry": {
        "pythagorean": "c = √(a² + b²)",
        "pyramid-volume": "V = (1/3)·A·h",
        "ellipse-area": "A = π·a·b",
        "polygon-interior-angle": "内角 = (n−2)·180°/n",
        "torus-volume": "V = 2π²·R·r²",
        "sphere-volume": "V = (4/3)·π·r³",
        "sphere-surface-area": "S = 4·π·r²",
        "rectangle-diagonal": "d = √(w² + h²)",
        "cube-properties": "V = a³, S = 6a², d = a√3",
    },
    "economics": {
        "gdp-growth-rate": "g = (GDP_t − GDP_{t−1})/GDP_{t−1} × 100%",
        "labor-force": "LF = E + U",
        "labor-force-participation": "LFP = LF/Pop × 100%",
        "marginal-product-labor": "MPL = ΔQ/ΔL",
        "nominal-to-real": "实际 = 名义/(1+π)",
        "okuns-law": "Δu ≈ −½(g − g*)",
        "average-propensity-consume": "APC = C/Y",
        "mpc-from-multiplier": "MPC = 1 − 1/k",
        "tax-multiplier": "k_t = −MPC/(1−MPC)",
        "balance-of-trade": "BoT = X − M",
        "fisher-equation": "i = r + π",
        "marginal-propensity-consume": "MPC = ΔC/ΔY",
    },
    "securities": {
        "yidongpingjunxian-ma-jincha-sichatishi": "MA_n = (P_1+…+P_n)/n；金叉=短期MA上穿长期MA",
        "peg-ratio": "PEG = PE/g",
        "margin-requirement": "保证金比例 = 权益/持仓市值 × 100%",
        "current-yield": "CY = 年息/现价",
        "beta-covariance": "β = Cov(r_i,r_m)/Var(r_m)",
        "price-to-book": "P/B = 股价/每股账面价值",
        "market-risk-premium": "MRP = r_m − r_f",
        "annualized-volatility": "σ_年 = σ_日×√252",
        "annualized-vol": "σ_年 = σ_日×√252",
        "market-cap": "市值 = 股价×总股本",
        "max-drawdown": "MDD = (峰值−谷值)/峰值 × 100%",
        "earnings-yield": "盈利收益率 = EPS/P × 100%",
        "option-breakeven-call": "看涨盈亏平衡 = K + 权利金",
        "option-breakeven-put": "看跌盈亏平衡 = K − P",
        "dividend-payout": "股利支付率 = DPS/EPS",
        "fcf-yield": "FCF收益率 = FCF/股价 × 100%",
        "book-to-market": "B/M = BVPS/P",
    },
    "banking": {
        "bond-current-yield": "当前收益率 = 年息/价格",
        "debt-to-income": "DTI = 月债/月收 × 100%",
        "net-worth": "净资产 = 资产 − 负债",
        "break-even-savings": "X = r_l/(r_d+r_l)",
        "apy-calculator": "APY = (1+r/n)^n − 1",
        "perpetuity-pv": "PV = C/r",
        "nominal-from-effective": "r = n·((1+EAR)^{1/n} − 1)",
        "tax-equivalent-yield": "TEY = 免税收益/(1−税率)",
        "loan-to-value": "LTV = 贷款/抵押物价值 × 100%",
    },
    "tax": {
        "ad-valorem-duty": "从价税 = 计税价×税率",
        "specific-duty": "从量税 = 数量×单位税额",
        "reverse-charge": "代扣代缴 = 代扣金额×征收率",
        "capital-gains-effective": "应缴税 = 收益×优惠税率",
        "foreign-tax-credit": "可抵扣 = min(境外已纳, 抵免限额)",
        "vat-output": "销项税额 = 销售额×税率",
        "tax-to-gdp": "宏观税负 = 税收/GDP × 100%",
        "average-tax-rate": "平均税率 = 总税/总收入",
        "social-security-tax": "社保费 = 基数×费率",
        "tax-credit": "实缴 = max(应纳税额−抵免, 0)",
    },
    "insurance": {
        "annuity-certain-pv": "PV = C·(1−(1+i)^−n)/i",
        "annuity-nsp": "净单保费 = 年给付 × äₙ",
        "annuity-present": "PV = PMT·(1−(1+i)^−n)/i",
        "average-severity": "平均赔付额 = 总赔款/索赔件数",
        "calc-1": "豁免保费现值 = Σ 未缴保费_t/(1+i)^t",
        "calc-28": "毛保费 = 纯保费/(1−附加费率)",
        "calc-pv-1": "PV = FV/(1+i)^n",
        "claim-frequency": "理赔频率 = 理赔次数/风险暴露",
        "claim-reserve": "准备金 = 终极赔款 − 已付赔款",
        "combined-ratio": "综合成本率 = (赔款+费用)/保费 × 100%",
        "complete-life-expectancy": "eₓ = Σ t·ₜpₓ",
        "endowment-premium": "两全保费 = 身故现值 + 满期现值",
        "estimate-20": "现金价值 = 准备金 × 退保比例",
        "expected-claim-loss": "期望损失 = 频率 × 严重度",
        "expense-ratio-ins": "费用率 = 运营费用/保费收入 × 100%",
        "expense-ratio": "费用率 = 营运费用/保费",
        "force-of-mortality": "μₓ = −ln(pₓ)",
        "gross-premium-loading": "毛保费 = 纯保费 × (1+附加费率)",
        "ibnr-estimate": "IBNR = 终极赔款 × (1−已付比例)",
        "ibnr-reserve": "IBNR = 已发生赔款 − 已报告赔款",
        "level-premium-life": "年保费 = 趸缴保费/äₙ",
        "life-cover-need": "寿险保额 = 年收入缺口 × 折现年金因子",
        "loss-ratio-ins": "赔付率 = 赔款支出/保费收入 × 100%",
        "loss-ratio": "赔付率 = 已决赔款/保费",
        "mortality-prob": "死亡率 qₓ = 1−pₓ",
        "net-single-premium": "NSP = Σ 给付_t/(1+i)^t",
        "premium-calc": "保费 = 保额 × 费率",
        "premium-elasticity": "弹性 = (Δ需求/需求)/(Δ保费/保费)",
        "pure-premium-rate": "纯费率 = 期望损失/暴露单位",
        "pure-premium": "期望损失 = 频率 × 严重度",
        "siwanglv-shengmingbiao-yubaofeigoucheng": "qₓ = 1−pₓ；保费 = 保额×利率因子",
        "stats-5": "赔付率 = 已发生/已报告",
        "surrender-value": "现金价值 = 准备金 × 退保比例",
        "survival-prob-t": "ₜpₓ = lₓ₊ₜ/lₓ",
        "uw-margin": "承保利润 = 保费 × (1−综合成本率)",
        "uw-profit": "承保利润 = 保费 − 赔款 − 费用",
    },
    "accounting": {
        "amortization-intangible": "年摊销 = (原值−残值)/年限",
        "asset-turnover": "资产周转率 = 营收/总资产",
        "break-even-units": "盈亏平衡量 = FC/(P−VC)",
        "calc-1": "应纳增值税 = 销项税额 − 进项税额",
        "calc-2": "预缴所得税 = 利润 × 税率",
        "cash-conversion-cycle": "CCC = DSO + DIO − DPO",
        "contribution-margin": "单位边际贡献 = 单价 − 单位变动成本",
        "current-ratio": "流动比率 = 流动资产/流动负债",
        "days-payable-outstanding": "DPO = 应付账款/营业成本 × 365",
        "days-sales-outstanding": "DSO = 应收账款/营收 × 365",
        "debt-service-coverage": "DSCR = OCF/债务偿付额",
        "debt-to-asset": "资产负债率 = 负债总额/资产总额",
        "depreciation-declining": "年折旧 = 账面净值 × 2/年限",
        "depreciation-straight": "年折旧 = (原值−残值)/年限",
        "depreciation-syd": "年折旧 = (原值−残值)×剩余年数/年数总和",
        "ebit": "EBIT = 营收 − 营业成本 − 费用",
        "ebitda": "EBITDA = EBIT + 折旧 + 摊销",
        "free-cash-flow": "FCF = OCF − 资本支出",
        "gross-margin": "毛利率 = (收入−成本)/收入 × 100%",
        "gross-profit": "毛利 = 营收 − 营业成本",
        "interest-coverage": "利息保障倍数 = EBIT/利息费用",
        "inventory-days": "DIO = 存货/营业成本 × 365",
        "inventory-turnover": "存货周转率 = 销售成本/平均存货",
        "net-profit-margin": "净利率 = 净利/收入 × 100%",
        "operating-cash-flow": "OCF = 净利润 + 折旧摊销 − 营运资本变动",
        "quick-ratio": "速动比率 = (流动资产−存货)/流动负债",
        "roa-calc": "ROA = 净利/总资产 × 100%",
        "roe-calc": "ROE = 净利/净资产 × 100%",
        "roe-dupont": "ROE = 净利率 × 资产周转率 × 权益乘数",
        "working-capital": "营运资金 = 流动资产 − 流动负债",
    },
    "surveying": {
        "area-24": "地籍面积 = Σ 各宗地多边形面积（坐标法）",
        "area-25": "房产面积 = 套内面积 + 分摊共有面积",
        "area-calc": "A = 长 × 宽（矩形）或 ½|Σ(x_i·y_{i+1}−x_{i+1}·y_i)|",
        "area-coordinates": "A = ½|Σ(x_i·y_{i+1} − x_{i+1}·y_i)|",
        "bearing-azimuth": "α = atan2(Δy, Δx)",
        "bearing-from-coordinates": "α = atan2(ΔE, ΔN)",
        "bearing-to-offset": "ΔE = D·sinα, ΔN = D·cosα",
        "calc-1": "平差改正数 v_i = −f_h/n（闭合差均摊）",
        "calc-86": "道路中线/横断面：按桩号与要素计算",
        "calc-angle-2": "十进制 = 度 + 分/60 + 秒/3600",
        "chord-length-curve": "c = 2R·sin(Δ/2)",
        "circular-curve": "T=R·tan(Δ/2), L=R·Δ, E=R(sec(Δ/2)−1), M=R(1−cos(Δ/2))",
        "convert-32": "高斯投影：经纬度 ↔ 平面直角坐标",
        "convert-33": "平距 D=√(S²−v²), 高差 v=S·sinα",
        "convert-34": "UTM ↔ 经纬度 分带换算",
        "convert-50": "GIS 数据格式/坐标转换",
        "coordinate-convert": "坐标转换：仿射或七参数",
        "coordinate-distance-2d": "d = √((x₂−x₁)²+(y₂−y₁)²)",
        "coordinate-distance-3d": "d = √(Δx²+Δy²+Δz²)",
        "coordinate-rotation": "x'=x·cosθ−y·sinθ, y'=x·sinθ+y·cosθ",
        "cut-fill-volume": "V = (A₁+A₂)/2 · L（相邻断面）",
        "distance-4": "平距 = √(S²−v²)（斜距改正）",
        "distance-calc": "d = √(Δx²+Δy²)",
        "earthwork-pyramid-volume": "V = ⅓·A·h",
        "elevation-diff": "闭合差 f_h = Σh − (H_终−H_起)",
        "end-area-volume": "V = (A₁+A₂)/2 · L",
        "external-distance-curve": "E = R(sec(Δ/2)−1)",
        "grade-angle": "坡度 i = tanα × 100%",
        "grade-intersection-elev": "y = y₀ + i·x + x²/(2R)",
        "horizontal-distance": "D_h = S·cosα",
        "horizontal-from-slope": "平距 = 斜距·cos(垂直角)",
        "leveling-calc": "H_i = H_{i−1} + 后视 − 前视",
        "map-scale": "实地长 = 图上长 × 比例尺分母",
        "middle-ordinate-curve": "M = R(1−cos(Δ/2))",
        "prismoidal-volume": "V = (A₁+4A_m+A₂)/6 · L",
        "ratio-7": "比例尺 = 图上距 / 实地距",
        "reduced-level-bsfs": "H_i = H_{i−1} + BS − FS",
        "scale-converter": "图上长 = 实地长 / 比例尺分母",
        "shuizhunceliangbihechayuyunxuwucha": "允许闭合差 = ±k·√L",
        "stadia-distance": "D = K·l·cos²α + C·cosα",
        "subtense-distance": "D = b/(2·tan(θ/2))",
        "tangent-length-curve": "T = R·tan(Δ/2)",
        "triangulation-side": "a/sinA = b/sinB = c/sinC",
        "vertical-curve-elev": "抛物线竖曲线 y = ax²+bx+c",
    },
    "energy": {
        "air-purifier-area": "适用面积 ≈ CADR × 0.1 (m²)",
        "assessor-water-quality": "TDS 评级：按阈值分段判定水质",
        "battery-capacity-wh": "Wh = Ah × V",
        "battery-life": "续航 = 容量(Wh) / 功耗(W)",
        "calc-area-air": "适用面积 = CADR × 0.1",
        "calc-voltage-capacity": "串联 V=ΣV_i；并联 Ah=ΣAh_i",
        "calculator-calc-4": "分贝叠加 L = 10·log₁₀(Σ10^(L_i/10))",
        "calculator-calc-5": "COP = 制热量 / 耗电量",
        "calculator-calc-carbon": "碳排放 = 活动量 × 排放因子",
        "calculator-calc-power-usage": "阶梯电费 = Σ 各档电量 × 档位电价",
        "calculator-calc-power": "待机功耗 = 功率 × 时间",
        "carbon-footprint": "碳足迹 = Σ(活动量 × 排放因子)",
        "carnot-efficiency": "η = 1 − T_c/T_h",
        "conductive-heat-rate": "Q = k·A·ΔT/d",
        "convert-emission": "CO₂当量 = 质量 × GWP",
        "cop-heatpump": "COP = Q/W",
        "daily-irradiation": "日辐照量 = 峰值 × 等效日照时数",
        "electrical-power": "P = V × I",
        "energy-consumption": "E = P × t",
        "energy-cost": "电费 = P × t × 电价",
        "energy-density": "能量密度 = E/m",
        "energy-efficiency": "能效 = 输出 / 输入",
        "energy-from-power": "E = P × t",
        "energy-payback": "回收期 = 投资 / 年节约额",
        "estimate-area": "发电量 = 面积 × 辐照 × 效率 × 小时",
        "estimate-power": "估算功率 = 资源量 × 效率系数",
        "estimate-time-current": "充电时间 = 容量 / 电流",
        "fridge-power-estimator": "日耗电 ≈ 额定功率 × 24 × 负载系数",
        "fuel-cost": "费用 = 用量 × 单价",
        "fuel-heat-value": "热量 = 质量 × 低位热值",
        "gravitational-potential": "PE = m·g·h",
        "heat-energy-q": "Q = m·c·ΔT",
        "heat-pump-cop": "COP = Q/W",
        "joule-heating": "P = I²·R",
        "kinetic-energy": "KE = ½·m·v²",
        "lcoe": "LCOE = 生命周期成本 / 总发电量",
        "power-consumption": "用电 = P × t",
        "power-factor": "PF = P/S = cosφ",
        "r-value-insulation": "R = d/k",
        "solar-calculator": "发电 = 面积 × 辐照 × 效率",
        "solar-output-physics": "P = A × G × η",
        "solar-panel-power": "P = A × G × η",
        "specific-energy": "比能量 = E/m",
        "standby-power-calculator": "待机功耗 = Σ(P_i × t_i)",
        "thermal-efficiency": "η = 输出 / 输入",
        "three-phase-power": "P = √3·U·I·cosφ",
        "wind-power-estimator": "P = ½·ρ·A·v³·Cp",
        "wind-power-physics": "P = ½·ρ·A·v³·Cp",
        "wind-power": "P = ½·ρ·A·v³·Cp",
    },
    "meteorology": {
        "absolute-humidity": "AH = 216.7·e_s/(T+273.15)  (g/m³)",
        "air-aqi": "AQI = 逐污染物分段线性插值",
        "apparent-temperature": "AT = 体感温度（温湿风综合）",
        "beaufort-scale": "风速 v ↔ 蒲福风级 n",
        "calc-55": "月相照明率 = (1+cos φ)/2",
        "calc-84": "日照辐射量 = 辐照度 × 时长",
        "calc-temp-humidity-1": "露点 Td = 243.12γ/(17.62−γ)",
        "cloud-base-height": "h = (T−Td)/0.98 × 100 (m)",
        "dew-point": "露点 Td = Magnus 公式反解",
        "fengsu-zhenfeng-yufenglidengji": "风力等级 ↔ 风速 (m/s)",
        "heat-index": "HI = 体感指数（温湿综合）",
        "humidex": "Humidex = T + 0.5555·(e−10)",
        "humidity-1": "露点舒适度 = f(温度, 露点)",
        "isa-temperature": "T = 15 − 1.98·h (°C, h:km)",
        "jiangshuagailvguji": "降水概率 = 基于相似天气型估计",
        "precip-calc": "降水量 = 雨强 × 时长",
        "precip-rate": "降雨等级 = 分段阈值判定",
        "pressure-altitude": "h = 44308·(1−(P/1013.25)^0.1903)",
        "relative-humidity": "RH = e/e_s × 100%",
        "saturation-vapor-pressure": "e_s = 6.1078·exp(17.27T/(T+237.3))",
        "wet-bulb-temperature": "湿球温度 T_w（迭代近似）",
        "wind-chill": "WCI = 13.12+0.6215T−11.37v^0.16+0.3965Tv^0.16",
        "wind-direction": "风向方位 = 角度 → 16 方位",
        "ziwaixianzhishuyufangshaidengji": "UV 指数 = 分段分级",
    },
    "realestate": {
        "assessor-23": "成新率 = 1 − 已用年限/经济寿命",
        "assessor-38": "按揭月供 = 等额本息公式",
        "assessor-39": "计税评估值 = 计税依据 × 税率",
        "assessor-40": "保险重置价值 = 重建成本",
        "assessor-42": "征收补偿 = 区片价 × 面积",
        "assessor-43": "企业价值 = 资产 − 负债（或收益法）",
        "assessor-44": "无形资产评估 = 收益/市场/成本法",
        "assessor-45": "涉税评估值",
        "assessor-return": "V = NOI / 资本化率 R",
        "assessor-second-hand": "评估值 = 可比实例价 × 修正系数",
        "calc-1": "月供 = P·i·(1+i)^n/((1+i)^n−1)",
        "calc-2": "租金回报率 = 年租金/总价 × 100%",
        "calc-70": "楼面价 = 土地总价/总建筑面积",
        "calc-93": "比较法：评估值 = 案例价 × Π修正",
        "calc-assessor": "拆迁补偿 = 重置价 × 成新率 + 区位",
        "calc-cost": "资本机会成本 = 替代投资收益",
        "calc-return": "REITs 收益 = 分红/价格",
        "chiyou-qijianyunying-feiyong": "持有费用 = 税费+维护+管理",
        "convert-area-shared": "公摊 = 建筑面积 − 套内面积",
        "cost-depreciation": "年折旧 = (重置−残值)/使用年限",
        "cost-depreciation-1": "成本法：价值 = 重置成本 − 折旧 + 地价",
        "dengenbenxi-benjinyuegongxiangxichaijie": "月供拆解 = 本金+利息逐期",
        "depreciation-2": "房屋折旧 = (1−成新率)×重置成本",
        "down-payment": "首付 = 总价 × 首付比例",
        "estimate-37": "空置损失 = 潜在租金 × 空置率",
        "estimate-ratio-down-payment": "贷款额度 = (1−首付比例)×总价",
        "fangdichan-xintuo-jijinguzhi": "REITs 估值 = 资产净值/份额",
        "fund-loan": "公积金额度 = f(账户余额, 缴存)",
        "fund-loan-1": "可贷额度 = 余额×倍数 或 缴存法",
        "layout-score": "户型评分 = 综合指标加权",
        "market-valuation": "市场比较法：评估值 = 可比价×修正",
        "paimai-baoliujia-qipaijia-sheding": "起拍价 = 保留价×折扣",
        "price-discount-1": "实售价 = 标价×(1−折扣率)",
        "pv": "PV = Σ CF_t/(1+r)^t",
        "rent": "租售比 = 总价 / 年租金",
        "rent-1": "潜在毛收入 = 租金×面积×入住率",
        "return-1": "净收益 = 经营收入 − 运营费用",
        "return-2": "收益法：V = NOI / 资本化率",
        "rater-usable-layout": "得房率 = 套内/建筑面积 × 100%",
        "shichang-bijiaofa-anlixiuzheng": "案例修正 = 可比价×因素修正",
        "tudi-jizhundijia-luxianjia-xishuxiuzheng": "路线价 = 基准价×深度×宽深修正",
        "xianjinliuyuce": "现金流 = 经营现金流 − 资本支出",
        "yanglao-dichan-touzi-tuichu-jihui": "投资回报 = 收益/投入",
    },
    "sports": {
        "altitude-acclimatization": "海拔适应时间 = f(上升速率, 海拔)",
        "baofali-zongtiao-lidingtiaoyuan": "纵跳高度 h = v₀²/(2g)",
        "calc-61": "能量消耗 = MET × 体重 × 时间",
        "calc-62": "打击率 = 安打/打数；ERA = 自责分×9/局",
        "calc-angle-slope": "百分比坡度 = tanθ × 100%",
        "calc-heart-rate-1": "HRR = 最大心率 − 静息心率",
        "calc-length-cutting": "肌效贴裁剪长度 = 按需分摊",
        "calc-time": "NDL 免减压时间 = f(深度, 潜水时长)",
        "calculator-calc-9": "齿比 = 牙盘齿数 / 飞轮齿数",
        "calculator-calc-time": "配速 = 时间 / 距离",
        "convert-13": "攀岩难度等级转换（V ↔ YDS）",
        "convert-47": "1RM = 重量/(1.0278−0.0278×次数)",
        "convert-time": "转换时间 = 分段耗时之和",
        "detector-14": "无氧阈 = 乳酸拐点对应强度",
        "dianjiezhi-diushi-buchong": "电解质补充 = f(出汗量, 钠丢失)",
        "estimate-22": "运动补水 = 体重损失 × 系数",
        "estimate-35": "出汗率 = (运动前−后体重)/时间",
        "estimate-stamina": "背包负重消耗 = f(重量, 距离)",
        "estimate-tester": "VO2max = 15.3×距离(英里)/时间 + 3.5",
        "fitness-tracker": "健身指标追踪 = 综合记录",
        "gantangyuan-chubei-yunaili": "肝糖原储备 = 肝+肌糖原总量",
        "heart-rate-1": "最大心率 = 220 − 年龄",
        "heart-rate-3": "HRR 恢复 = (运动心率−恢复心率)/运动心率",
        "hongxibao-xieyang-shiyingxing": "红细胞携氧适应性",
        "jianzhong-tuoshui-buye-kongzhi": "减重补液 = 体重差×补液系数",
        "jixianwei-kuai-man-leixingtuice": "肌纤维类型 = 基于表现推测",
        "juzhongzongchengji-sinclair-xishu": "总成绩 = 抓举+挺举；Sinclair 系数修正",
        "lanqiumingzhonglv-lanbanxiaolv": "命中率 = 命中/出手；篮板效率 = 篮板/分钟",
        "lingmin-zhefanpao-chengji": "折返跑成绩 = f(用时, 距离)",
        "pingheng-biyandanjiao-shichang": "闭眼单脚时长 = 平衡指标",
        "ratio-18": "脂肪氧化比例 = f(运动强度)",
        "rehab-motion": "康复动作负荷 = 渐进式",
        "rouren-qianqu-cequ-jinbu": "柔韧进步 = 前屈差值",
        "shejiansanbubanjing": "散布半径 = √(Σd²/n)",
        "sheyangdonglixuebanshi": "VO2 半时 = ln2/动力学常数",
        "shuimianhuifuzhiliang": "睡眠恢复 = f(时长, 深睡)",
        "speed-5": "速度 = 距离/时间；加速度 = Δv/Δt",
        "speed-6": "击剑弓步速度 = 距离/时间",
    },
    "math": {
        "arithmetic-mean-math": "均值 x̄ = Σx_i/n",
        "arithmetic-series-sum": "S = n(a₁+a_n)/2",
        "calc-1": "百分比 = 部分/整体 × 100%",
        "calc-2": "比例 a:b = a/b",
        "calc-3": "c = √(a²+b²)",
        "calc-4": "圆面积 A = πr², 周长 C = 2πr",
        "calculus-tools": "导数/积分 = 微积运算",
        "circular-permutation": "环形排列数 = (n−1)!",
        "combination-repetition": "可重复组合 C(n+k−1, k)",
        "determinant-2x2": "|A| = ad − bc",
        "distance-2d": "d = √((x₂−x₁)²+(y₂−y₁)²)",
        "dot-product": "a·b = Σ a_i·b_i",
        "exponent-solve": "x = log_a(b) = ln b/ln a",
        "factorial-calc": "n! = n×(n−1)×…×1",
        "gcd-lcm": "gcd(a,b)·lcm(a,b) = |a·b|",
        "geometric-series-sum": "S = a₁(1−rⁿ)/(1−r)",
        "geometry-calculator": "面积/体积 = 几何公式",
        "herons-area": "A = √(s(s−a)(s−b)(s−c))",
        "law-of-cosines": "c² = a²+b²−2ab·cosC",
        "law-of-sines": "a/sinA = b/sinB = c/sinC",
        "modulo-calc": "a mod b",
        "multinomial-coefficient": "n!/(n₁!·n₂!·…·n_k!)",
        "nth-term-geometric": "a_n = a₁·r^(n−1)",
        "percent-change": "Δ% = (新−旧)/旧 × 100%",
        "power-calc": "x^y",
        "prime-check": "试除法判定素数",
        "quadratic-discriminant": "Δ = b²−4ac",
        "quadratic-solver": "x = (−b±√Δ)/2a",
        "root-calc": "√x, ∛x",
        "slope-line": "k = (y₂−y₁)/(x₂−x₁)",
    },
    "robotics": {
        "accel-distance": "s = v²/(2a)",
        "battery-runtime": "t = 容量(Wh) / 功耗(W)",
        "cable-tension-pulley": "单侧绳张力 T = mg/2",
        "centripetal-speed-limit": "v_max = √(a_max·R)",
        "dc-motor-back-emf": "E = K_e·ω",
        "diff-drive-velocity": "v=(v_r+v_l)/2, ω=(v_r−v_l)/L",
        "encoder-angle-resolution": "Δθ = 360°/PPR",
        "end-effector-reach": "L₁−L₂ ≤ r ≤ L₁+L₂",
        "forward-kinematics-2r": "x=L₁cosθ₁+L₂cos(θ₁+θ₂)",
        "gear-ratio-speed": "n_out = n_in / i",
        "gear-ratio-torque": "T_out = T_in · i",
        "gravity-comp-torque": "τ = m·g·r·cosθ",
        "inverse-kinematics-2r": "θ₂ = acos((x²+y²−L₁²−L₂²)/(2L₁L₂))",
        "joint-angular-velocity": "ω = v / L",
        "lifting-torque": "τ = m·g·r",
        "linear-accel-force": "F = m·a",
        "motor-power": "P = τ·ω",
        "pid-controller": "u = Kp·e + Ki·∫e + Kd·ė",
        "rotational-inertia-torque": "τ = I·α",
        "servo-pwm-angle": "角度 = (脉宽−最小)/(最大−最小)×180°",
        "stepper-step-angle": "步距角 = 360°/(步数/圈)",
        "stereo-depth": "Z = f·B/d",
        "trajectory-time-linear": "t = s / v",
        "wheel-odometry": "Δs=(d_r+d_l)/2, Δθ=(d_r−d_l)/L",
    },
    "geology": {
        "dicengqingjiaoyuzouxiang-jiandanluopan": "倾角/走向 = 罗盘读数换算",
        "dijichengzailijisuan": "承载力 = f(土性, 深度, 宽度)",
        "dip-strike": "走向/倾角 = 测量换算",
        "diqiuhuaxueyichangjieshi": "地球化学异常解释 = 背景+衬值",
        "diqiuwulishujujisuan": "地球物理数据计算",
        "diqiuwuliyingyong": "地球物理应用 = 反演解释",
        "duanceng-xingzhi-weiyi-huodongxing-panding": "断层判定 = f(产状, 位移)",
        "dizhibianlujilubiao": "编录参数 = 分层计算",
        "estimate-grade-reserve": "品位储量 = 品位 × 体积 × 体重",
        "estimate-reserve-1": "断面法 V = Σ(A_i×L_i)",
        "hardness-strength": "摩氏硬度 ↔ 抗压强度",
        "hazard": "地质灾害风险 = f(坡度, 岩性, 降雨)",
        "huanjingdizhipingjia": "环境地质评价 = 综合分级",
        "kengtan-chuanmai-yanmai-quyang-fangshi": "坑探设计 = 工程布置",
        "richter-scale": "M_L = log10(A) + 距离修正",
        "sample-1": "槽探设计 = 规格×采样",
        "sanweidizhijianmocanshu": "三维建模参数 = 网格/插值",
        "shuiwendizhishentoushiyan": "渗透系数 k = Q/(A·i)",
        "slope": "临界角 θ_c = arctan(μ)",
        "soil-sample": "采样设计 = 网度布置",
        "spacing-4": "勘探网度 = 工程间距布置",
        "tester-16": "岩石力学参数 = 强度/变形计算",
    },
    "investment": {
        "annuity-fv-inv": "FV = PMT·((1+i)^n−1)/i",
        "annuity-pv-inv": "PV = PMT·(1−(1+i)^−n)/i",
        "bond-price": "P = Σ C/(1+y)^t + F/(1+y)^n",
        "bond-ytm-approx": "YTM ≈ (C+(F−P)/n)/((F+P)/2)",
        "cagr": "CAGR = (EV/BV)^(1/n) − 1",
        "capm-return": "E(R) = Rf + β·(Rm−Rf)",
        "discounted-payback": "折现回收期 = 累计折现现金流回正年限",
        "dividend-payout-ratio": "股利支付率 = DPS/EPS",
        "dividend-yield": "股息率 = 年股息 / 股价",
        "eps-calc": "EPS = (净利−优先股)/流通股数",
        "future-value-inv": "FV = PV·(1+r)^n",
        "geometric-mean-return": "G = (Π(1+r_i))^(1/n) − 1",
        "holding-period-return": "HPR = (P₁−P₀+D)/P₀",
        "irr-calc": "NPV = Σ CF_t/(1+r)^t = 0",
        "npv-calc": "NPV = Σ CF_t/(1+r)^t",
        "payback-period": "回收期 = 累计现金流由负转正年限",
        "pe-ratio": "P/E = 股价 / 每股收益",
        "portfolio-beta": "βp = Σ w_i·β_i",
        "portfolio-return": "E(Rp) = Σ w_i·R_i",
        "present-value-inv": "PV = FV/(1+r)^n",
        "profitability-index": "PI = 现值 / 初始投资",
        "real-rate-return": "实际 = (1+名义)/(1+通胀) − 1",
        "retention-ratio": "留存率 = 1 − 股利支付率",
        "roi-calc": "ROI = (收益 − 成本)/成本",
        "sharpe-ratio": "Sharpe = (Rp−Rf)/σp",
        "sortino-ratio": "Sortino = (Rp−Rf)/σd",
        "sustainable-growth": "g = ROE × 留存率",
        "yield-spread": "利差 = 债券收益率 − 基准收益率",
    },
    "science": {
        "astronomy-toolkit": "天文观测 = 坐标/历算/视差",
        "calc-2": "理想气体 PV = nRT",
        "calc-4": "密度 ρ = m/V",
        "calc-5": "v = d/t",
        "calc-area-volume": "几何面积/体积 = 标准公式",
        "calc-cycle": "分子量 = Σ(原子量×个数)",
        "calc-distance": "地理距离 = Haversine 公式",
        "calc-stats": "均值/方差/标准差 = 统计量",
        "calculator-calc": "科学计算 = 函数求值",
        "centripetal-force": "F_c = m·v²/r",
        "coulomb-force": "F = k·q₁·q₂/r²",
        "doppler-effect": "f' = f·(v±v_o)/(v∓v_s)",
        "electric-field-point": "E = k·q/r²",
        "geo-distance-calculator": "Haversine d = 2R·asin(√(...))",
        "meteor-crater-estimator": "撞击坑直径 = f(能量, 密度)",
        "molar-mass-calculator": "摩尔质量 = Σ(原子量×个数)",
        "pendulum-period": "T = 2π·√(L/g)",
        "polar-day-night": "极昼极夜 = f(纬度, 节气)",
        "projectile-range": "R = v²·sin(2θ)/g",
        "provident-fund": "公积金 = 缴存基数×比例",
        "spring-oscillation-period": "T = 2π·√(m/k)",
        "star-magnitude-compare": "m₁−m₂ = −2.5·log(L₁/L₂)",
        "tide-height-estimator": "潮汐高度 = 天文+气象分潮",
        "work-done": "W = F·d·cosθ",
        "xianxingfangchengzuqiujie-2yuan-3yuan": "线性方程组 = 代入/消元",
        "yiyuanercifangchengqiujie": "x = (−b±√(b²−4ac))/2a",
        "convert-5": "进制转换 = 按权展开",
        "convert-power": "物理单位换算 = 量纲换算",
    },
    "hydraulic": {
        "bernoulli-velocity": "P + ½ρv² + ρgh = 常数",
        "buoyancy-force": "F = ρ·g·V",
        "continuity-pipe": "Q = A·v",
        "darcy-head-loss": "h_f = f·(L/D)·v²/(2g)",
        "hazen-williams-headloss": "h_f = 10.67·L·Q^1.852/(C^1.852·d^4.87)",
        "hydrostatic-pressure": "p = ρ·g·h",
        "manning-flow": "v = (1/n)·R^(2/3)·S^(1/2)",
        "orifice-discharge": "Q = C_d·A·√(2gh)",
        "pump-power": "P = ρ·g·Q·H/η",
        "rectangular-weir": "Q = (2/3)·C_d·b·√(2g)·H^(3/2)",
        "reynolds-number": "Re = ρ·v·D/μ",
        "velocity-from-flow": "v = Q/A",
        "flow-power": "P = ρ·g·Q·H",
        "calc-1": "管道压降 = 沿程+局部损失",
        "calc-2": "水泵扬程 H = 几何扬程 + 损失",
        "calc-26": "明渠均匀流 v = (1/n)R^(2/3)S^(1/2)",
        "calc-54": "水闸启闭力 = 总水压力 + 摩擦",
        "calc-power-2": "换热功率 Q = k·A·ΔT",
        "calc-pressure-capacity": "蓄能器容量 = 容积×压力系数",
        "calc-protection": "水锤 Δp = ρ·a·Δv",
        "calc-speed-itinerary": "液压缸推力 F = p·A",
        "area-15": "库容曲线 = f(水位, 面积)",
        "area-capacity": "库容 = ∫面积 dH",
        "density-4": "填筑密度 = 干密度控制",
        "daba-wendingxing-kanghua-kangqingfu": "抗滑安全系数 K = Σ抗滑/Σ滑动力",
        "daohongxi-shuitousunshi-maishen": "倒虹吸水头损失 = 沿程+局部",
        "flow": "溢洪道泄流 Q = m·b·√(2g)·H^(3/2)",
        "flow-1": "生态下泄流量 = 多年均值×系数",
        "flow-pipeline": "引水管径 D = √(4Q/(πv))",
        "gear-1": "液压泵排量 = 流量/转速",
        "kinematic-viscosity": "ν = μ/ρ",
        "minor-head-loss": "h_L = ξ·v²/(2g)",
        "power-3": "泵站效率 η = 输出/输入",
        "power-torque": "液压马达 T = p·V/(2π)",
        "pressure-drop": "壁厚 δ = p·D/(2σ)",
        "pressure-flow-1": "液压阀流量 Q = C_d·A·√(2Δp/ρ)",
        "qudao-buchong-buyu-liusu": "渠道不冲流速 = f(土质)",
        "shenliu-daxidinglv-yudixiashuiwei": "达西定律 q = k·i·A",
        "shenliu-jinrunxian-weizhi": "浸润线 = 浸润曲线",
        "speed-pressure": "液压回路 v = Q/A",
        "temp-7": "温度应力 σ = E·α·ΔT",
        "yeyayouxiangsheji": "油箱容积 = 泵流量×系数",
        "yuji-nisha-kurongsunshi": "淤积损失 = 入库沙量×沉降率",
    },
    "fire": {
        "calc-extinguish-extinguisher": "灭火器配置 = 保护面积/单具保护面积（向上取整）",
        "calc-water-pressure-hydrant": "最不利点栓口压力 ≥ 0.35 MPa（规范）",
        "estimate-speed-smoke": "烟雾蔓延速度 = 层化模型",
        "estimate-time-flow": "疏散时间 = 行走 + 排队",
        "evacuation-time": "t = N/(b·D·f) + 行走时间",
        "extinguisher-calc": "灭火器最大保护距离/配置基准（GB 50140）",
        "hydrant-pressure": "栓口动压 = 几何高差 + 沿程 + 局部",
    },
    "machinery": {
        "area-dosage-1": "涂装用量 = 面积 × 膜厚 × 密度",
        "banjinzhewanzhankai": "展开长度 = 中性层 + 折弯补偿",
        "belt-drive-1": "传动比 i = n₁/n₂ = d₂/d₁",
        "calc-64": "装配间隙/过盈 = 公差配合",
        "calc-89": "离合器转矩 T = μ·F·R·Z",
        "calc-gear-1": "齿轮模数 m = d/z",
        "calc-gear-3": "齿轮参数 = 标准模数系列",
        "calc-gear": "标准齿轮 d = m·z",
        "calc-lifespan-belt": "皮带寿命 = f(张力, 转速)",
        "calc-strength": "轴强度 σ = M/W",
        "calc-weld": "焊缝强度 = 焊脚×长度×强度",
        "convert-hardness-strength": "硬度 ↔ 抗拉强度（经验公式）",
        "drive-2": "蜗杆效率 η = tanλ/tan(λ+ρ)",
        "elasticity-1": "刚度 k = F/δ",
        "energy-2": "制动能耗 = ½mv²",
        "estimate-gravity": "重心 = Σ(m_i·x_i)/Σm_i",
        "estimate-lifespan-bearing": "L10 = (C/P)^p·10⁶/(60n)",
        "frequency-17": "隔振频率比 = f/√k/m",
        "gear": "齿轮设计 = 强度/几何计算",
        "lifespan-bearing-1": "轴承额定动载 C = f(寿命, 转速)",
        "lifespan-bearing": "轴承寿命 L10 = (C/P)^p",
        "pressure-4": "花键挤压 σ = F/(d·l·z)",
        "runhuaxitongsheji": "润滑油量 = f(功率, 转速)",
        "speed-cutting-feed": "切削速度 v = π·d·n/1000",
        "strength-14": "键连接剪切 τ = F/(d·l)",
        "strength-15": "链条拉力 = 功率/速度",
        "strength-6": "键强度 = 挤压/剪切校核",
        "strength-7": "铆接剪切 τ = F/(n·πd²/4)",
        "stretch": "弹簧刚度 k = G·d⁴/(8D³n)",
        "tanhuangsheji": "弹簧设计 k = G·d⁴/(8D³n)",
        "temp-hardness": "热处理硬度 = f(温度, 冷却)",
        "thread-drive": "螺纹升角 λ = arctan(p/(πd))",
        "thread-recognize": "螺纹识别 = 参数查表",
        "tolerance": "配合公差 = 孔轴偏差",
        "tolerance-1": "几何公差 = 标注查表",
        "xiao-dingwei-lianjie-chicun": "销连接 d = √(4F/(π·τ))",
        "zaoyin-shengya-pinpu-jiangzao-yugu": "噪音预估 = 声压级叠加",
        "zhujian-bamoxiedu-sheji": "拔模斜度 = f(壁厚, 材料)",
        "zhineng-wurenyugaoxiaoduibijisuanqi": "对比评分 = 指标加权",
    },
    "metalwork": {
        "banjin-jianzhe-chongya-maohan-gongyi": "钣金工艺 = 剪折/冲压/铆焊",
        "calc-feed": "铣削进给 f = v_c/(π·d·n)",
        "calc-gear-2": "齿轮加工 = 滚齿/插齿参数",
        "calc-pressure-mold": "冲压力 F = L·t·τ",
        "calc-stretch": "拉伸率 = (L−L₀)/L₀ × 100%",
        "carbon-8": "渗碳层深 = f(温度, 时间)",
        "detector-21": "无损检测 = 方法选择",
        "diandonggongju-xifen": "电动工具细分 = 选型",
        "forging-ratio": "锻造比 = A₀/A",
        "forging": "锻造伸长 = 锤击次数×单次",
        "hardness": "硬度—热处理关系 = 经验曲线",
        "laxue-ladao-chisheng-lali-sheji": "拉削拉力 F = p·b·z",
        "lifespan-1": "电池寿命 = 容量/负载",
        "pinpaijiazhipinggujisuan": "品牌价值 = 收益法评估",
        "pressure-casting": "铸造方法 = 选型",
        "qiege-denglizi-huoyan-shuidao-canshu": "切割参数 = 功率/速度匹配",
        "resistance-2": "焊接方法 = 选型",
        "sheet-bend": "钣金折弯展开 = 中性层法",
        "speed-itinerary": "刨削速度 = 行程/时间",
        "surface-finish": "表面粗糙度 = Ra 对照",
        "tangxue-tangdao-tanggan-jingdu-kongzhi": "镗削精度 = 公差控制",
        "temp-forging": "锻造温度 = 材料相图区间",
        "thread": "螺纹加工 = 方案选择",
        "voltage-current": "焊接电流 I = f(板厚, 焊丝)",
        "welding-heat": "热输入 Q = η·U·I/v",
        "wushua-zhinengyuqingliangduibijisuanqi": "对比评分 = 指标加权",
        "yuanlingongju-xifen": "园林工具细分 = 选型",
        "zhineng-duogongnengyunaiyongduibijisuanqi": "对比评分 = 指标加权",
        "zulinfeilvjisuan": "租赁费率 = 原值×费率/周期",
    },
    "fishery": {
        "aerator-duration": "增氧机时长 = 溶氧缺口/(功率×效率)",
        "assessor-risk-4": "鱼病风险 = f(水温, 密度, 水质)",
        "breeding-cycle": "养殖周期 = 培育+养成+收获",
        "bulaowangmuchicunyuzuixiaokebuguige": "网目尺寸 = 最小可捕规格对应",
        "calc-39": "百分比 = 部分/整体 × 100%",
        "calc-power": "加热功率 P = V·ρ·c·ΔT/t",
        "cycle-6": "清淤周期 = f(淤积速率)",
        "density-1": "放养密度 = 尾/亩（优化）",
        "dissolved-oxygen": "溶氧预测 = f(温度, 气压)",
        "drug-withdrawal-fish": "休药期 = 基准×(温度校正)",
        "estimate-23": "浮游生物量 = 计数×体积换算",
        "estimate-emission-wastewater": "COD 估算 = 投饵×系数",
        "feed-calculator": "饲料量 = 体重×投喂率",
        "feed-protein-fat": "蛋白脂肪配比 = 营养需求",
        "feed-rate-calculator": "投喂率 = 体重×率%",
        "feeding-rate": "投喂率 = 体重×日率",
        "fish-disease-risk": "鱼病风险 = 综合评分",
        "fish-growth-curve": "生长曲线 = 特定生长率拟合",
        "fish-weight": "鱼体重 = a·体长^b",
        "fry-transport-survival": "运输成活率 = f(密度, 温度, 时间)",
        "harvest-size-price": "规格价格 = 均重×单价",
        "mesh-size-guide": "网目尺寸 = 最小可捕规格",
        "oxygen-machine": "增氧机配置 = 需氧量/单机功率",
        "parasite-lifecycle": "寄生虫周期 = 温度依赖模拟",
        "plankton-biomass": "浮游生物量 = 计数×体积",
        "pond-capacity": "承鱼量 = f(面积, 溶氧, 换水)",
        "pond-desilting": "清淤周期 = 淤积/清除速率",
        "price-1": "规格价格 = 均重×系数",
        "profit-calculator": "利润 = 收入 − 成本",
        "ratio-11": "饲料配比 = 蛋白/脂肪需求",
        "ratio-hormone": "催产激素剂量 = 体重×系数",
        "salinity-calculator": "盐度 = 盐质量/水体积",
        "seafood-cold-storage": "冷藏温度 = 保质期对应",
        "spawning-hormone": "催产剂量 = 体重×系数",
        "stocking-density": "放养密度 = 优化承载",
        "tank-volume": "V = 长 × 宽 × 高",
        "temp-3": "冷藏温度 = 保质期对应",
        "temp-4": "休药期 = 基准×(温度校正)",
        "temp-density": "运输成活率 = f(温度, 密度)",
        "wastewater-cod": "COD 估算 = 投饵×排放系数",
        "water-exchange-rate": "换水率 = 流量/池体积",
        "water-quality-1": "换水率 = 流量/池体积",
        "water-quality-threshold": "氨氮/亚盐安全阈值 = 查表",
        "water-quality": "氨氮/亚盐阈值 = 查表",
        "winter-heating": "加热功率 = V·ρ·c·ΔT/t",
        "yuleishengzhangquxian-tedingshengzhanglv-nihe": "特定生长率 G = (lnW₂−lnW₁)/(t₂−t₁)",
        "yutangrongyangliang-shuiwen-qiya-yuce": "溶氧预测 = f(水温, 气压)",
        "zengyangjikaiqishichang-rongyangxiajiangmoxing": "开启时长 = 溶氧下降/增氧速率",
    },
    "ecommerce": {
        "calc-79": "增长率 = (本期−同期)/同期 × 100%",
        "calc-commission-2": "佣金 = 成交额 × 费率",
        "conversion-4": "转化率 = 成交/观看",
        "discount": "实付 = 标价 × (1−折扣率)",
        "erp-dingdan-caigou-duijie": "ERP 对接 = 数据映射",
        "estimate-ranking": "排名 = 权重×因子",
        "inventory-1": "补货点 = 日均销×提前期 + 安全库存",
        "kaidian-yunyingyuguizeduibijisuanqi": "对比评分 = 指标加权",
        "kedan-jiandanjia-liandailv": "客单价 = 销售额/订单数",
        "pingjia-chaping-tuihuo-lv": "退货率 = 退货/成交",
        "response-2": "客服响应 = 时效统计",
        "wuliu-fahuo-cangchu-gongyinglian-zhenghe": "物流整合 = 路径优化",
        "wuliu-lanshou-qianshou-shixiao": "物流时效 = 揽收→签收时长",
    },
    "procurement": {
        "assessor-26": "供应商准入分 = 指标加权",
        "calc-1": "EOQ = √(2DS/H)",
        "calc-15": "EOQ = √(2DS/H)",
        "cost": "到岸成本 = 货价 + 运费 + 关税",
        "inventory-turnover": "周转率 = 年销售成本/平均库存",
        "rater-price": "供应商评分 = 综合加权",
        "supplier-score": "综合评分 = 质量×交期×价格×服务",
        "turnover-inventory": "周转天数 = 365/周转率",
        "wuliu-yunshufangshi-yunfei-bidui": "运费比对 = 方式×距离×重量",
        "zhaobiao-gongkai-yaoqing-jingzheng-fangshi": "招标方式 = 公开/邀请/竞争",
    },
    "property": {
        "area-shared": "公摊 = 建筑面积 − 套内面积",
        "calc-shared-property-fee": "物业费 = 面积 × 单价",
        "calculator-calc-area-1": "物业费分摊 = 面积×单价/户数",
        "cleaning-allocation": "保洁分配 = 区域/频次覆盖",
        "cost-profit": "预算 = 成本 + 收入 − 利润",
        "elevator-energy": "电梯能耗 = 次数 × 单次能耗",
        "energy": "能耗分摊 = 用量 × 单价",
        "estimate-energy-elevator": "电梯能耗估算 = 次数×功率×时长",
        "fee-allocation": "物业费分摊 = 面积比例",
        "irrigation-schedule": "浇灌排程 = 需水量/流量",
        "rater-performance": "绩效考核 = 指标加权评分",
        "response-1": "维修响应时效 = 报修到响应时长",
        "response-4": "维修完成时效 = 报修到完成时长",
    },
    "hr": {
        "assessor-training-hr": "培训评估 = 需求/效果加权",
        "attendance-stats": "考勤统计 = 出勤/缺勤/加班",
        "bandwidth-1": "薪酬带宽 = 中位×(1±分位%)",
        "calc-81": "内推激励 = 基数×系数",
        "eap-xinli-zixun-weiji-ziyuan": "EAP 资源 = 咨询匹配",
        "hris-zizhuyuaiduibijisuanqi": "对比评分 = 指标加权",
        "insurance-hr": "五险一金 = 基数 × 比例",
        "performance-ranking": "归一化排名 = 得分/最大值",
        "performance-score": "绩效 = 指标加权",
        "recruitment-funnel": "招聘转化 = 各阶段/上一阶段",
        "social-insurance": "社保 = 基数 × 缴费比例",
        "tracking-hours": "培训学时 = 累计 − 缺口",
        "training-hr": "年度学时累计 = Σ课时",
    },
    "language": {
        "calc-1": "词汇量估算 = f(测试正确率, 词表)",
        "calc-2": "阅读速度 = 字数 / 时间",
        "chengyujielongyouxi-neizhichengyuku": "成语接龙 = 首尾字匹配",
        "convert-14": "拼音转换 = 汉字→拼音（规则映射）",
        "hanyuyanwenchaijie-yuanyin-fuyin": "谚文拆解 = 元音+辅音组合",
        "riyuwushiyintulianxi-dianjifayin": "五十音 = 假名发音练习",
        "stats-2": "字符统计 = 汉字+英文+标点计数",
        "xibanyayuzhongyinweizhipanduan-neizhiguize": "西语重音 = 规则判定",
        "yingyucigen-cizhuijiyika-jiaohukapian": "词根记忆 = 卡片抽取",
    },
    "legal": {
        "arbitration-fee": "仲裁费 = 标的×费率（分段）",
        "calc-16": "诉讼时效届满日 = 起算日 + 期间",
        "estimate-salary": "劳动争议赔偿 = 工资×年限×系数",
        "falv-yijian-han-beiwanglu-bianxie": "法律意见书 = 模板生成",
        "falvwenshuguanjiancizidongtiqu": "关键词提取 = 文本匹配",
        "feisu-ipo-simu-binggou-yewu": "非诉业务 = 类型匹配",
        "food-safety": "退一赔十 = 价款 × 10（或损失×3）",
        "hetongshengxiao-zhongzhiriqijiaoyan": "合同日期校验 = 生效/终止比对",
        "housing-fund-loan": "公积金贷款 = f(余额, 缴存)",
        "inheritance-share": "继承份额 = 法定比例分配",
        "ipr-damages": "侵权赔偿 = 损失/获利/许可费",
        "jicheng-yizhu-gongzheng-yichan-fenpei": "遗产分配 = 遗嘱/法定",
        "labor-compensation-n1": "N+1 补偿 = (N+1) × 月薪",
        "labor-compensation": "经济补偿 = N × 月薪（封顶）",
        "late-payment-interest": "逾期利息 = 本金 × 日利率 × 天数",
        "lawyer-fee-reference": "律师费 = 标的×费率（指导价）",
        "legal-age": "法定年龄 = 当前 − 出生日期",
        "legal-calculator": "法律计算 = 通用公式",
        "legal-reference": "法律查询 = 条文匹配",
        "loan-statute-limitations": "借款时效 = 起算 + 3年",
        "marriage-property-agreement": "婚姻财产 = 共同/个人划分",
        "notarization-fee": "公证费 = 标的×费率",
        "overtime-pay": "加班费 = 基数 × 150%/200%/300%",
        "patent-fee-calculator": "专利费 = 年费×年度",
        "patent-term-calculator": "专利有效期 = 申请日 + 20年",
        "personal-injury": "人身损害 = 医疗费+误工+残疾",
        "rent-deposit": "租房押金 = 月租 × 倍数",
        "severance-pay": "违法解除 2N = 2N × 月薪",
        "social-security-base": "社保基数 = 工资（上下限）",
        "stamp-duty-legal": "印花税 = 金额 × 税率",
        "statute-limitations": "诉讼时效 = 起算 + 期间",
    },
    "fun": {
        "convert-speed-stride": "速度 = 步频 × 步幅",
        "caishuzi-1-100fanwei": "猜数字 = 二分查找提示",
        "lucky": "幸运数字 = 算法映射",
        "analysis-4": "血型性格 = 描述匹配",
    },
    "dentistry": {
        "assessor-5": "氧化锆透光率 = 分光测量",
        "bite-contact": "咬合平衡 = 接触点分析",
        "calc-1": "DMFT = 龋数 + 失数 + 补数",
        "caries-risk": "Cariogram 龋病风险 = 加权评分",
        "estimate-27": "咬合力 = 测量/参考值",
        "gingival-index": "牙龈指数 GI = 分级评分",
        "implant-dimensions": "种植体选择 = f(骨量, 美学)",
        "kouqiangai-tnm-shaichagongju": "口腔癌 TNM = 分期筛查",
        "kouqiangkuiyang-afuta-fenqi": "口腔溃疡分期 = 大小/病程",
        "length-1": "根管工作长度 = X线测量",
        "length-2": "种植体 = f(骨量, 修复空间)",
        "length-3": "牙弓长度 = 发育评估",
        "oral-cancer-screening": "口腔癌 TNM = 分期筛查",
        "oral-ulcer": "口腔溃疡分期 = 病程分级",
        "orthodontic-force": "正畸力 = 牙移动需求",
        "quankouyichi-heweiguanxi-zhuanyi": "颌位关系 = 转移记录",
        "ratio-13": "牙槽骨吸收 = 根长比例分级",
        "salivary-flow": "唾液流率 = 测量评估",
        "shezhen-zhongyi-yukouqiangjiankang": "舌诊 = 特征匹配",
        "sialography": "腺体造影 = 导管形态判读",
        "tongue-oral-health": "舌诊关联 = 特征匹配",
    },
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--industry", required=True)
    ap.add_argument("--map", default=None, help="JSON 字符串 {slug: 公式}")
    args = ap.parse_args()
    mapping = MAPPINGS.get(args.industry, {})
    if args.map:
        mapping.update(json.loads(args.map))
    if not mapping:
        print("无映射，退出"); return
    stats = {}
    for slug, eq in mapping.items():
        r = inject(args.industry, slug, eq)
        stats[r] = stats.get(r, 0) + 1
    print("行业 %s: %s" % (args.industry, stats))


if __name__ == "__main__":
    main()
