#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""真实化 content_deepdive 中 design/ 第 1~69 个 key（analysis ~ mesh-gradient）。
占位变体：第二十八种「快速核对<Title>：优先统一输入单位、口径和参数范围，再对典型样例做一遍手工验算」
summary 原 None、faqs 仅 2 条。
改写为真实设计/前端/图像/音频/摄影场景：summary + 3 scenarios + 1 example(body) + 3 faqs。
统一补「纯前端本地处理、结果以浏览器实时计算为准、样式代码仅作快速产出参考、正式项目以设计系统与实测为准」免责，不覆盖 title。
"""
import json, os

P = 'i18n/tools/content_deepdive.json'
d = json.load(open(P, encoding='utf-8'))

DIS = '结果以浏览器实时计算为准，纯前端本地处理、数据不上传；生成的样式与代码仅作快速产出参考，正式项目请以设计系统、规范与浏览器实测为准。'

DATA = {
 'analysis': dict(
   summary='上传图片后用 Canvas 分析像素，提取主色与完整调色板及占比，便于从参考图快速获取配色方案。',
   scenarios=['从品牌参考图、海报或插画中提取主色，统一 UI 与物料配色。',
              '把竞品截图丢进去，快速拿到对方色板做风格对标。',
              '为 PPT、封面或社媒图从一张主视觉图派生协调的辅助色。'],
   example=dict(title='从一张渐变封面提取 6 色调色板',
     body='<p><strong>输入：</strong>上传一张 1200×800 的渐变封面图。</p><p><strong>处理：</strong>Canvas 逐像素统计颜色频次，合并相近色并取前 6 个主色，计算各自占比。</p><p><strong>输出：</strong>主色 HEX 列表（如 #FF6B35 占 31%、#7C3AED 占 24%…）及占比条形，可一键复制为 CSS 变量。</p>'),
   faqs=[dict(q='大图会卡吗？', a='提取在浏览器本地用 Canvas 完成，建议先缩到 2000px 以内；像素越多统计越慢但仍是本地运算，不上传服务器。'),
         dict(q='占比是怎么算的？', a='按颜色量化后的像素数量除以总像素；相近色会先做合并再排序，因此占比是近似视觉分布，非精确色彩管理数值。'),
         dict(q='能直接导出给设计软件吗？', a='可复制 HEX 或导出 CSS 变量片段，再粘进 Figma、代码或设计系统即可，'+DIS)]),
 'audio-recorder': dict(
   summary='基于浏览器 MediaRecorder 录制麦克风音频，支持试听、下载与格式选择，纯本地采集。',
   scenarios=['录制一段口播或会议片段做本地备份与回听。',
              '采集环境音做播客、视频配音的前期试录。',
              '快速录一段语音备忘，下载后转给同事。'],
   example=dict(title='录制 30 秒人声并下载 WEBM',
     body='<p><strong>输入：</strong>点击开始，对着麦克风说话 30 秒。</p><p><strong>处理：</strong>MediaRecorder 采集本地音频流并编码。</p><p><strong>输出：</strong>生成可试听的 WEBM/OGG 片段，提供下载按钮，数据全程不离开本机。</p>'),
   faqs=[dict(q='需要联网吗？', a='不需要，录音用浏览器原生 API 在本地完成；如浏览器未授权麦克风则无法采集。'),
         dict(q='为什么是 WEBM 而不是 MP3？', a='浏览器原生录制多输出 WEBM/OGG，MP3 需额外编码库；如需 MP3 可下载后用转换工具处理。'),
         dict(q='录音有长度限制吗？', a='主要受内存与浏览器限制，长按会持续占用内存；'+DIS)]),
 'avatar-generator': dict(
   summary='根据昵称、配色与形状参数生成卡通头像图片，支持下载，用于账号默认头像。',
   scenarios=['为新账号快速生成一个有辨识度的默认头像。',
              '批量给团队成员生成风格统一的占位头像。',
              '做活动页的虚拟用户头像装饰。'],
   example=dict(title='用昵称 "Niao" 生成圆角方形头像',
     body='<p><strong>输入：</strong>昵称 Niao、主色 #FF6B35、形状圆角方形。</p><p><strong>处理：</strong>按昵称哈希派生图形与配色，绘制几何组合。</p><p><strong>输出：</strong>预览头像图，可下载 PNG 用作头像。</p>'),
   faqs=[dict(q='头像会重复吗？', a='由昵称哈希派生，同昵称同参数会得到相同图形；不同昵称通常不同，但不保证全局唯一。'),
         dict(q='能上传自己的照片吗？', a='本工具按参数生成卡通图形，不处理真人照片；如需真人头像请用图片裁剪类工具。'+DIS)]),
 'aztec-code': dict(
   summary='将文本或网址编码为 Aztec 二维码（二维矩阵码），支持尺寸与导出。',
   scenarios=['生成工单、票务用的 Aztec 码做线下核验。',
              '为物料印刷生成可扫描的 Aztec 二维码。',
              '演示 Aztec 与 QR 的编码差异。'],
   example=dict(title='编码 "TB-2026-009" 为 Aztec',
     body='<p><strong>输入：</strong>文本 TB-2026-009、模块尺寸 4px。</p><p><strong>处理：</strong>按 Aztec 规范编码为中央同心方阵。</p><p><strong>输出：</strong>可下载的 Aztec 码图片，扫码即得原文。</p>'),
   faqs=[dict(q='Aztec 和 QR 有什么区别？', a='Aztec 以中心同心方为核心、无需静区，常用于票据交通；QR 更普及。两者都属二维矩阵码。'),
         dict(q='能存多少字符？', a='取决于纠错与版本，短文本足够；过长会超出容量无法生成。'+DIS)]),
 'badge-generator': dict(
   summary='可视化生成徽章（shields 风格标签），调节文字、配色与形状并导出 SVG/图片。',
   scenarios=['给开源项目或文档做状态徽章。',
              '生成"已通过/进行中"等流程标签贴到页面。',
              '做活动海报的小角标装饰。'],
   example=dict(title='生成 "build|passing" 绿色徽章',
     body='<p><strong>输入：</strong>左文本 build、右文本 passing、配色绿。</p><p><strong>处理：</strong>按 shields 比例绘制左右双色胶囊。</p><p><strong>输出：</strong>SVG 徽章，可下载或复制链接。</p>'),
   faqs=[dict(q='能直接用在 GitHub 吗？', a='可下载 SVG 后随仓库提供，或自托管链接引用；本工具只生成图形不托管。'),
         dict(q='文字太长怎么办？', a='会按字符宽度自适应加长，过长建议缩写。'+DIS)]),
 'base64-to-image': dict(
   summary='将 Base64 图片字符串还原为可预览、可下载的图片文件。',
   scenarios=['调试接口返回的 Base64 缩略图时还原查看。',
              '把内联 data URI 转成图片文件保存。',
              '确认一段 Base64 是否为有效图片。'],
   example=dict(title='还原一段 PNG data URI',
     body='<p><strong>输入：</strong>data:image/png;base64,iVBORw0…（截断）。</p><p><strong>处理：</strong>解码 Base64 为二进制并识别格式。</p><p><strong>输出：</strong>预览图与下载按钮，可保存为 .png。</p>'),
   faqs=[dict(q='支持哪些格式？', a='按 data URI 中的 MIME 识别，常见 PNG/JPEG/WEBP/GIF 均可；非图片数据会报错。'),
         dict(q='解码会泄露数据吗？', a='完全在本地完成，不上传。'+DIS)]),
 'blueprint-grid': dict(
   summary='生成蓝图风格网格背景（深底+浅线），可调格距与线宽，导出 CSS/图片。',
   scenarios=['给工程、架构类页面做背景纹理。',
              '做线框原型时的底纹。',
              '演示网格系统的视觉。'],
   example=dict(title='生成 20px 蓝图网格',
     body='<p><strong>输入：</strong>格距 20px、主线色 #9DB2FF、底 #0B1E3B。</p><p><strong>处理：</strong>绘制双层网格背景。</p><p><strong>输出：</strong>预览与 CSS background 代码，可复制。</p>'),
   faqs=[dict(q='能导出图片吗？', a='可导出为平铺背景图或 CSS，用于网页背景。'+DIS)]),
 'border-radius-generator': dict(
   summary='可视化调整四角圆角并实时生成 CSS，支持单独角与百分比。',
   scenarios=['调卡片、按钮、头像的圆角。',
              '做不规则有机形状（花瓣/水滴）。',
              '统一设计系统的圆角 token。'],
   example=dict(title='生成左上 24px、右下 50% 圆角',
     body='<p><strong>输入：</strong>TL 24px、TR 8px、BR 50%、BL 8px。</p><p><strong>处理：</strong>拼接 border-radius 简写。</p><p><strong>输出：</strong>实时预览与 <code>border-radius:24px 8px 50% 8px;</code> 代码。</p>'),
   faqs=[dict(q='百分比是相对什么？', a='相对元素自身的宽高，因此方形与长条形会得到不同弧度。'+DIS)]),
 'bpm-tapper': dict(
   summary='通过点击/空格敲击测出节拍速度（BPM），支持平均与稳定度提示。',
   scenarios=['跟鼓点或音乐点击测出歌曲 BPM。',
              '给练琴、跑步配速找节奏。',
              '验证一段节奏是否稳定。'],
   example=dict(title='连点 8 次得 120 BPM',
     body='<p><strong>输入：</strong>按节奏点击 8 次。</p><p><strong>处理：</strong>取相邻间隔中位数推算 BPM 并平滑。</p><p><strong>输出：</strong>显示约 120 BPM 及偏差范围。</p>'),
   faqs=[dict(q='点不准怎么办？', a='多点几次取中位数更稳；前 2 拍因样本少会波动，属正常。'+DIS)]),
 'breakpoint-queries': dict(
   summary='按设备区间生成响应式媒体查询断点与容器代码，便于移动端适配。',
   scenarios=['搭一套手机/平板/桌面的断点。',
              '把设计稿的 375/768/1280 转成媒体查询。',
              '检查现有断点是否覆盖主流视口。'],
   example=dict(title='生成 3 档断点',
     body='<p><strong>输入：</strong>断点 640/1024/1440px。</p><p><strong>处理：</strong>生成 min-width 媒体查询块。</p><p><strong>输出：</strong>可直接粘贴的 CSS 断点代码。</p>'),
   faqs=[dict(q='用 min 还是 max 好？', a='移动优先多用 min-width 向上增强；视项目习惯，二者可互转。'+DIS)]),
 'button-generator': dict(
   summary='可视化生成按钮样式（圆角、阴影、渐变、悬停），导出 CSS。',
   scenarios=['快速产出 CTA 按钮样式。',
              '统一一套按钮变体（主/次/幽灵）。',
              '做邮件或落地页按钮。'],
   example=dict(title='生成橙色主按钮',
     body='<p><strong>输入：</strong>底色 #FF6B35、圆角 12px、阴影柔和。</p><p><strong>处理：</strong>组合背景、边框、内边距与悬停。</p><p><strong>输出：</strong>按钮预览与完整 CSS。</p>'),
   faqs=[dict(q='悬停态怎么处理？', a='生成 :hover 的明度/位移变化，可直接用。'+DIS)]),
 'card-generator': dict(
   summary='生成卡片容器样式（圆角、边框、阴影、内边距），导出 CSS。',
   scenarios=['做内容卡片、商品卡。',
              '统一列表项卡片视觉。',
              '给原型快速套卡片壳。'],
   example=dict(title='生成白底圆角卡',
     body='<p><strong>输入：</strong>白底、圆角 16px、轻阴影、内距 20px。</p><p><strong>处理：</strong>组合背景/边框/阴影。</p><p><strong>输出：</strong>卡片预览与 CSS。</p>'),
   faqs=[dict(q='阴影多重合适？', a='卡片多用单层柔阴影；层级越高阴影越扩散，具体以设计系统为准。'+DIS)]),
 'checker': dict(
   summary='对颜色、对比度或数值做快速校验，给出通过与建议。',
   scenarios=['核查两色对比度是否达 WCAG。',
              '校验输入数值是否在合理范围。',
              '做提交前的快速自检。'],
   example=dict(title='校验 #FFF 与 #767676 对比度',
     body='<p><strong>输入：</strong>前景 #767676、背景 #FFFFFF。</p><p><strong>处理：</strong>按 WCAG 相对亮度算对比度。</p><p><strong>输出：</strong>对比度约 4.54:1，达 AA 普通文本。</p>'),
   faqs=[dict(q='AA 和 AAA 怎么选？', a='普通文本 AA 需 ≥4.5:1、AAA ≥7:1；大文本阈值更低。'+DIS)]),
 'checkerboard-generator': dict(
   summary='生成棋盘格图案背景，可调格大小与双色，导出 CSS/图片。',
   scenarios=['做透明区占位背景。',
              '视觉演示或游戏棋盘底。',
              '纹理装饰。'],
   example=dict(title='生成 16px 灰白棋盘',
     body='<p><strong>输入：</strong>格 16px、色 #EEE/#FFF。</p><p><strong>处理：</strong>用 conic/linear 渐变拼棋盘。</p><p><strong>输出：</strong>平铺背景预览与 CSS。</p>'),
   faqs=[dict(q='能做成动画吗？', a='本工具生成静态图；动画需另加 keyframes。'+DIS)]),
 'color-contrast-check': dict(
   summary='按 WCAG 计算两色对比度并判定 AA/AAA 达标情况，辅助无障碍配色。',
   scenarios=['确认正文/背景配色可读。',
              '核查按钮文字与底色。',
              '做无障碍合规自检。'],
   example=dict(title='检测深紫底白字',
     body='<p><strong>输入：</strong>文字 #FFFFFF、背景 #7C3AED。</p><p><strong>处理：</strong>算相对亮度差得对比度。</p><p><strong>输出：</strong>对比度约 5.9:1，AA/AAA 普通文本通过。</p>'),
   faqs=[dict(q='大文本阈值？', a='≥18.66px 粗体或 ≥24px 普通文本，AA 只需 ≥3:1。'+DIS)]),
 'color-palette': dict(
   summary='展示与浏览调色板（预设或自定义），复制色值，辅助配色选型。',
   scenarios=['挑选品牌色板。',
              '对照 Material/Tailwind 预设。',
              '给原型快速上色。'],
   example=dict(title='浏览暖橙调色板',
     body='<p><strong>输入：</strong>选暖橙预设。</p><p><strong>处理：</strong>列出明度梯度色。</p><p><strong>输出：</strong>色块与 HEX，可逐个复制。</p>'),
   faqs=[dict(q='能存自己的色板吗？', a='可临时编辑复制；持久化请保存到设计系统或导出。'+DIS)]),
 'color-palette-generator': dict(
   summary='按基色或情绪生成协调调色板（互补/类似/三角），导出变量。',
   scenarios=['从主色派生整套 UI 配色。',
              '做海报、PPT 的配色方案。',
              '给新品牌起一组色。'],
   example=dict(title='由 #FF6B35 生成类似色板',
     body='<p><strong>输入：</strong>基色 #FF6B35、类型类似。</p><p><strong>处理：</strong>在 HSL 空间取邻近色相。</p><p><strong>输出：</strong>5 色协调板与 HEX，可复制为 CSS 变量。</p>'),
   faqs=[dict(q='互补和类似怎么选？', a='类似色柔和统一，互补色对比强；按画面张力需求选。'+DIS)]),
 'color-picker': dict(
   summary='在画布/取色区选取颜色，显示 HEX/RGB/HSL 多格式并可复制。',
   scenarios=['从设计稿取一个准色。',
              '调出某颜色的 HSL 值。',
              '比对屏幕两处色差。'],
   example=dict(title='取橙色得 HEX/RGB/HSL',
     body='<p><strong>输入：</strong>在色域点选橙区。</p><p><strong>处理：</strong>读出该点颜色。</p><p><strong>输出：</strong>#FF6B35 / rgb(255,107,53) / hsl(16,100%,60%)，可复制。</p>'),
   faqs=[dict(q='屏幕色准吗？', a='受显示器校色影响，仅作近似参考；印刷以专色为准。'+DIS)]),
 'color-scheme-generator': dict(
   summary='生成明/暗或品牌配色方案（背景、表面、文字、强调），输出变量。',
   scenarios=['搭一套暗色主题变量。',
              '由品牌色生成中性+强调色。',
              '给设计系统补 token。'],
   example=dict(title='由主色生成暗色方案',
     body='<p><strong>输入：</strong>主色 #FF6B35、模式暗。</p><p><strong>处理：</strong>派生背景/表面/文字层级。</p><p><strong>输出：</strong>--bg/--surface/--text/--accent 等变量。</p>'),
   faqs=[dict(q='暗色背景多深合适？', a='常用 #0F172A/#1E293B 层级，文字需保证对比度达标。'+DIS)]),
 'color-shade-generator': dict(
   summary='从基色生成明度/饱和度梯度（50~900），输出多档色值。',
   scenarios=['生成组件的 state 色阶。',
              '做图表序列色。',
              '补设计系统的 shade。'],
   example=dict(title='生成橙色彩阶 50~900',
     body='<p><strong>输入：</strong>基色 #FF6B35。</p><p><strong>处理：</strong>在 OKLCH/HSL 上推明度梯度。</p><p><strong>输出：</strong>50/100/…/900 共 10 档 HEX。</p>'),
   faqs=[dict(q='为什么不用固定加减？', a='人眼对亮度的感知非线性，按感知均匀色彩空间推更自然。'+DIS)]),
 'color-temperature-converter': dict(
   summary='在开尔文色温与 RGB 之间换算，用于白平衡与灯光配色。',
   scenarios=['把 6500K 转成屏幕白点 RGB。',
              '估算烛光/日光灯的颜色。',
              '调摄影白平衡参考。'],
   example=dict(title='6500K 转 RGB',
     body='<p><strong>输入：</strong>色温 6500K。</p><p><strong>处理：</strong>按近似 Planck 曲线映射。</p><p><strong>输出：</strong>约 rgb(255,255,255)，即标准日光白。</p>'),
   faqs=[dict(q='低色温偏什么？', a='偏低（如 2700K）偏暖黄，偏高（如 9000K）偏冷蓝。'+DIS)]),
 'contrast-checker': dict(
   summary='检查前景/背景对比度与可读性，给出 WCAG 等级建议。',
   scenarios=['复核正文可读性。',
              '核查图标与底色。',
              '无障碍走查。'],
   example=dict(title='灰字白底核查',
     body='<p><strong>输入：</strong>前景 #6B7280、背景 #FFFFFF。</p><p><strong>处理：</strong>算对比度。</p><p><strong>输出：</strong>约 4.5:1，普通文本 AA 临界通过。</p>'),
   faqs=[dict(q='临界 4.5 安全吗？', a='刚好达标；低视力用户仍吃力，建议略高于阈值。'+DIS)]),
 'css-animation-generator': dict(
   summary='可视化编排 CSS 关键帧动画，调时长/缓动/属性并实时预览，导出 @keyframes。',
   scenarios=['做 hover/入场动画。',
              '给 loading、卡片做动效。',
              '教学演示 keyframes。'],
   example=dict(title='生成淡入上浮动画',
     body='<p><strong>输入：</strong>0% 透明下移 8px、100% 不透明归位、0.4s ease。</p><p><strong>处理：</strong>生成 keyframes。</p><p><strong>输出：</strong>@keyframes 与调用类，可复制。</p>'),
   faqs=[dict(q='性能注意什么？', a='优先动画 transform/opacity，避免触发 layout 的属性。'+DIS)]),
 'css-border-radius': dict(
   summary='生成 CSS 圆角代码，支持四角独立与百分比。',
   scenarios=['卡片/图片圆角。',
              '胶囊形按钮。',
              '不规则形状。'],
   example=dict(title='生成胶囊圆角',
     body='<p><strong>输入：</strong>四角 999px。</p><p><strong>处理：</strong>输出 border-radius。</p><p><strong>输出：</strong>border-radius:999px; 预览胶囊形。</p>'),
   faqs=[dict(q='999px 是圆角吗？', a='足够大时即胶囊/椭圆，是常见写法。'+DIS)]),
 'css-box-shadow-generator': dict(
   summary='拖动调整盒阴影偏移/模糊/扩散/颜色，生成单层或多层 CSS 阴影。',
   scenarios=['做卡片悬浮阴影。',
              '做双层质感阴影。',
              '内阴影凹陷效果。'],
   example=dict(title='生成柔和投影',
     body='<p><strong>输入：</strong>x0 y8 模糊 24 扩散 0 色 rgba(0,0,0,.12)。</p><p><strong>处理：</strong>拼 box-shadow。</p><p><strong>输出：</strong>预览与 CSS，可加多层。</p>'),
   faqs=[dict(q='多层阴影怎么写？', a='用逗号分隔多个 shadow 值即可叠加。'+DIS)]),
 'css-grid-generator': dict(
   summary='可视化配置 CSS Grid 行列与间距，生成 grid-template 代码。',
   scenarios=['搭页面整体栅格。',
              '做卡片网格布局。',
              '响应式列数实验。'],
   example=dict(title='生成 3 列自适应网格',
     body='<p><strong>输入：</strong>列 repeat(3,1fr)、间距 16px。</p><p><strong>处理：</strong>输出 grid 模板。</p><p><strong>输出：</strong>display:grid;… 代码与预览。</p>'),
   faqs=[dict(q='1fr 是什么？', a='剩余空间的一份，配合 repeat 可自适应列宽。'+DIS)]),
 'css-text-shadow': dict(
   summary='生成文字阴影 CSS，支持多层与发光效果。',
   scenarios=['标题描边/发光。',
              '水印文字。',
              '霓虹效果。'],
   example=dict(title='生成霓虹发光字',
     body='<p><strong>输入：</strong>0 0 8px #00C9A7 两层。</p><p><strong>处理：</strong>拼 text-shadow。</p><p><strong>输出：</strong>预览与 CSS。</p>'),
   faqs=[dict(q='多层怎么排？', a='逗号分隔，先画的后层叠在下。'+DIS)]),
 'data-matrix': dict(
   summary='将文本编码为 Data Matrix 二维矩阵码，支持尺寸导出。',
   scenarios=['工业标签、元件追溯码。',
              '物料印刷二维码。',
              '与 Aztec/QR 对比演示。'],
   example=dict(title='编码序列号 DM',
     body='<p><strong>输入：</strong>SN2026X、模块 4px。</p><p><strong>处理：</strong>按 Data Matrix 规范编码方阵。</p><p><strong>输出：</strong>可下载矩阵码，扫码得原文。</p>'),
   faqs=[dict(q='和 QR 怎么选？', a='Data Matrix 在小元件打标常用、容错好；消费场景多用 QR。'+DIS)]),
 'depth-of-field-calculator': dict(
   summary='按焦距、光圈、物距估算景深与前景/后景清晰范围，辅助摄影对焦。',
   scenarios=['拍人像虚化预估。',
              '风光大景深设置。',
              '微距拍摄景深判断。'],
   example=dict(title='50mm f/1.8 距 2m',
     body='<p><strong>输入：</strong>焦距 50mm、光圈 f/1.8、物距 2m、弥散圆 0.03mm。</p><p><strong>处理：</strong>按景深公式算前后清晰界。</p><p><strong>输出：</strong>景深约 0.09m，虚化明显。</p>'),
   faqs=[dict(q='弥散圆怎么取？', a='按传感器与输出尺寸经验值，一般 0.02~0.03mm；不同标准结果略有差异。'+DIS)]),
 'dot-pattern': dict(
   summary='生成圆点阵列背景图案，调点距/大小/色，导出 CSS/图片。',
   scenarios=['做波点背景。',
              '纹理装饰。',
              '包装/海报底纹。'],
   example=dict(title='生成 20px 波点',
     body='<p><strong>输入：</strong>距 20px、点径 3px、色 #FF6B35。</p><p><strong>处理：</strong>radial-gradient 平铺。</p><p><strong>输出：</strong>预览与 CSS。</p>'),
   faqs=[dict(q='点距和清晰度？', a='点距越小越密；过密在屏幕上易糊，以实测为准。'+DIS)]),
 'exposure-triangle-calculator': dict(
   summary='在光圈、快门、ISO 三者间换算等效曝光，辅助手动摄影。',
   scenarios=['调一档参数保持曝光。',
              '理解曝光三角关系。',
              '弱光提高 ISO 的代价估算。'],
   example=dict(title='快门放慢一档补光圈',
     body='<p><strong>输入：</strong>原 f/4、1/100、ISO100；改 f/5.6。</p><p><strong>处理：</strong>按档位守恒换算。</p><p><strong>输出：</strong>快门需 1/50 或 ISO 提一档保持曝光。</p>'),
   faqs=[dict(q='提 ISO 会怎样？', a='提 ISO 补亮度但噪点增；优先用光圈/快门，最后才加 ISO。'+DIS)]),
 'favicon-from-emoji': dict(
   summary='将单个 emoji 渲染为 favicon 图片，多尺寸导出。',
   scenarios=['给新站快速做图标。',
              '演示页临时图标。',
              '活动页趣味图标。'],
   example=dict(title='用 🔥 生成 favicon',
     body='<p><strong>输入：</strong>emoji 🔥、尺寸 64px。</p><p><strong>处理：</strong>Canvas 绘制 emoji。</p><p><strong>输出：</strong>ICO/PNG favicon 可下载。</p>'),
   faqs=[dict(q='所有 emoji 都能用吗？', a='取决于系统字体支持；个别平台渲染略有差异。'+DIS)]),
 'favicon-from-text': dict(
   summary='将文字/字母生成 favicon 图片，可调字体配色。',
   scenarios=['品牌首字母做图标。',
              '项目缩写标识。',
              '多站区分图标。'],
   example=dict(title='用 "TB" 生成图标',
     body='<p><strong>输入：</strong>文字 TB、底 #FF6B35、字白。</p><p><strong>处理：</strong>绘制圆底白字。</p><p><strong>输出：</strong>多尺寸 favicon 可下载。</p>'),
   faqs=[dict(q='几个字合适？', a='1~2 字最清晰；过多在小尺寸会糊。'+DIS)]),
 'favicon-generator': dict(
   summary='由图片或参数生成多尺寸 favicon 集，导出 ICO/PNG。',
   scenarios=['上线前补齐 favicon。',
              '从 logo 派生图标。',
              '生成 apple-touch 等尺寸。'],
   example=dict(title='由 logo 生成 16~256 集',
     body='<p><strong>输入：</strong>上传方形 logo。</p><p><strong>处理：</strong>多尺寸重绘。</p><p><strong>输出：</strong>ICO 与 PNG 套装可下载。</p>'),
   faqs=[dict(q='必须方形吗？', a='建议方形，非方会被裁切或留白；透明 PNG 更通用。'+DIS)]),
 'flexbox-generator': dict(
   summary='可视化配置 Flexbox 主轴/交叉轴/换行，生成 CSS 与预览。',
   scenarios=['做导航、卡片横排。',
              '垂直居中布局。',
              '响应式换行实验。'],
   example=dict(title='生成居中横排',
     body='<p><strong>输入：</strong>row、justify-center、align-center。</p><p><strong>处理：</strong>输出 flex 属性。</p><p><strong>输出：</strong>display:flex;… 代码与预览。</p>'),
   faqs=[dict(q='居中用哪个？', a='主轴 justify、交叉轴 align；两者都 center 即双向居中。'+DIS)]),
 'focal-length-equivalent': dict(
   summary='将镜头物理焦距按裁切系数换算等效全画幅焦距，便于视角比较。',
   scenarios=['比较不同画幅视角。',
              '选镜头前预估构图。',
              '理解 APS-C 系数。'],
   example=dict(title='35mm 在 APS-C(1.5x)',
     body='<p><strong>输入：</strong>物理 35mm、系数 1.5。</p><p><strong>处理：</strong>乘系数。</p><p><strong>输出：</strong>等效约 52.5mm，接近标准视角。</p>'),
   faqs=[dict(q='系数是什么？', a='传感器相对全画幅的裁切比，APS-C 多 1.5/1.6x，M4/3 约 2x。'+DIS)]),
 'font-pairing': dict(
   summary='推荐标题/正文字体搭配组合，辅助排版选型。',
   scenarios=['给网站选字体对。',
              '海报标题+正文搭配。',
              '品牌字体探索。'],
   example=dict(title='推荐无衬线标题+衬线正文',
     body='<p><strong>输入：</strong>风格现代。</p><p><strong>处理：</strong>给出搭配建议。</p><p><strong>输出：</strong>如 Plus Jakarta Sans + Noto Serif 组合与示例。</p>'),
   faqs=[dict(q='中文怎么配？', a='中文多用同族字重区分层级，西文再配一种点缀即可。'+DIS)]),
 'font-preview': dict(
   summary='输入文字预览各字体效果，对比字号字重。',
   scenarios=['选正文字体。',
              '对比同族字重。',
              '做字体规范样张。'],
   example=dict(title='预览 "ToolBox 工具箱"',
     body='<p><strong>输入：</strong>文字、字号 18/24、字重 400/700。</p><p><strong>处理：</strong>逐字体渲染。</p><p><strong>输出：</strong>并列预览，可比对。'+DIS+'</p>'),
   faqs=[dict(q='本地没有的字体？', a='仅显示浏览器已加载字体；未加载会回退默认。'+DIS)]),
 'generator-6': dict(
   summary='可视化调整盒阴影的偏移、模糊、扩散与颜色并生成 CSS，支持内阴影与多层。',
   scenarios=['做卡片悬浮阴影。',
              '做凹陷/凸起质感。',
              '多层叠加高级阴影。'],
   example=dict(title='生成双层投影',
     body='<p><strong>输入：</strong>层1 y2 模糊4 色淡、层2 y8 模糊24 色淡。</p><p><strong>处理：</strong>拼 box-shadow。</p><p><strong>输出：</strong>预览与 CSS，可复制。'+DIS+'</p>'),
   faqs=[dict(q='内阴影怎么开？', a='勾选 inset 关键字即内阴影。'+DIS)]),
 'generator-7': dict(
   summary='可视化设置边框宽度、样式、圆角与配色并生成 CSS，支持单边独立。',
   scenarios=['做卡片边框。',
              '分隔线/虚线。',
              '单边高亮。'],
   example=dict(title='生成底部 2px 橙线',
     body='<p><strong>输入：</strong>仅 bottom 2px solid #FF6B35。</p><p><strong>处理：</strong>拼 border 简写。</p><p><strong>输出：</strong>CSS 与预览。'+DIS+'</p>'),
   faqs=[dict(q='单边怎么写？', a='用 border-bottom 等单边属性，或四向简写配合 none。'+DIS)]),
 'generator-8': dict(
   summary='输入网址或文本生成可定制尺寸、容错与颜色的二维码，支持导出。',
   scenarios=['名片/海报放扫码入口。',
              '活动页快速出码。',
              '演示二维码参数。'],
   example=dict(title='生成含网址的二维码',
     body='<p><strong>输入：</strong>https://toolbox.example、容错 M、色 #1F2937。</p><p><strong>处理：</strong>编码为 QR 矩阵。</p><p><strong>输出：</strong>可下载二维码图片。'+DIS+'</p>'),
   faqs=[dict(q='容错越高越好吗？', a='越高越抗污损但越密；普通印刷 M/L 即可。'+DIS)]),
 'generator-9': dict(
   summary='输入数字生成 EAN-13 等常见条形码图片，自动算校验位，可下载。',
   scenarios=['商品标签打样。',
              '仓储演示条码。',
              '教学条码原理。'],
   example=dict(title='生成 EAN-13',
     body='<p><strong>输入：</strong>12 位数字。</p><p><strong>处理：</strong>算校验位并编码。</p><p><strong>输出：</strong>可下载条形码图片。'+DIS+'</p>'),
   faqs=[dict(q='校验位要自己填吗？', a='工具自动补第 13 位校验位，输入 12 位即可。'+DIS)]),
 'generator-10': dict(
   summary='以可视化方式编排 CSS 关键帧动画，调时长缓动与属性并实时预览，导出 @keyframes。',
   scenarios=['做入场/循环动画。',
              'loading 动效。',
              '教学 keyframes。'],
   example=dict(title='生成旋转动画',
     body='<p><strong>输入：</strong>0→360deg、1s linear infinite。</p><p><strong>处理：</strong>生成 keyframes。</p><p><strong>输出：</strong>@keyframes 与调用类。'+DIS+'</p>'),
   faqs=[dict(q='infinite 影响性能？', a='持续动画占主线程渲染，复杂场景注意降级。'+DIS)]),
 'generator-11': dict(
   summary='调参数生成可平铺重复的 CSS 背景纹理（点阵/网格/波浪），导出代码。',
   scenarios=['网页背景装饰。',
              '卡片底纹。',
              '活动页氛围。'],
   example=dict(title='生成点阵背景',
     body='<p><strong>输入：</strong>点径 2px、距 16px、色淡灰。</p><p><strong>处理：</strong>渐变平铺。</p><p><strong>输出：</strong>background 代码与预览。'+DIS+'</p>'),
   faqs=[dict(q='平铺会接缝吗？', a='参数取整除周期可无缝；否则会出现接缝。'+DIS)]),
 'generator-12': dict(
   summary='调粒子数量、速度、颜色与引力等参数实时预览粒子动画，导出 canvas 代码或图片。',
   scenarios=['网页背景特效。',
              '活动页粒子。',
              '教学 canvas 动画。'],
   example=dict(title='生成上浮粒子',
     body='<p><strong>输入：</strong>粒子 80、速度慢、橙白。</p><p><strong>处理：</strong>canvas 实时绘制。</p><p><strong>输出：</strong>预览与导出代码/图。'+DIS+'</p>'),
   faqs=[dict(q='粒子多了卡吗？', a='数量越大越耗 GPU/CPU，移动端建议降低数量。'+DIS)]),
 'glassmorphism-generator': dict(
   summary='生成毛玻璃（背景模糊+半透明+描边）效果 CSS，实时预览。',
   scenarios=['做悬浮卡片、导航。',
              '现代 UI 玻璃层。',
              '弹窗背景。'],
   example=dict(title='生成玻璃卡片',
     body='<p><strong>输入：</strong>模糊 12px、透明 .15、浅描边。</p><p><strong>处理：</strong>组合 backdrop-filter。</p><p><strong>输出：</strong>CSS 与预览，需底色衬托。'+DIS+'</p>'),
   faqs=[dict(q='为什么不显示模糊？', a='backdrop-filter 需背后有内容且浏览器支持；纯色底看不到效果。'+DIS)]),
 'gradient': dict(
   summary='生成线性/径向/圆锥渐变 CSS，调色标与角度，实时预览。',
   scenarios=['做按钮、横幅背景。',
              '卡片渐变描边。',
              '品牌渐变。'],
   example=dict(title='生成橙紫线性渐变',
     body='<p><strong>输入：</strong>135°、#FF6B35→#7C3AED。</p><p><strong>处理：</strong>拼 linear-gradient。</p><p><strong>输出：</strong>CSS 与预览。'+DIS+'</p>'),
   faqs=[dict(q='角度怎么算？', a='0° 向上，90° 向右，顺时针；可用 to 关键词。'+DIS)]),
 'gradient-from-color': dict(
   summary='由单个基色派生协调渐变（同色深浅或邻近色），一键生成。',
   scenarios=['快速出同色渐变。',
              '做按钮背景。',
              '补一套渐变变量。'],
   example=dict(title='由 #FF6B35 派生渐变',
     body='<p><strong>输入：</strong>基色 #FF6B35、类型同色深浅。</p><p><strong>处理：</strong>明暗两端取色。</p><p><strong>输出：</strong>渐变 CSS 与预览。'+DIS+'</p>'),
   faqs=[dict(q='同色还是邻近？', a='同色深浅更稳，邻近色更有层次；按需求选。'+DIS)]),
 'grid-pattern': dict(
   summary='生成网格线背景图案，调格距与线色，导出 CSS/图片。',
   scenarios=['原型底格。',
              '工程图背景。',
              '纹理。'],
   example=dict(title='生成 8px 网格',
     body='<p><strong>输入：</strong>格 8px、线 #E5E7EB。</p><p><strong>处理：</strong>linear 双向平铺。</p><p><strong>输出：</strong>background 代码与预览。'+DIS+'</p>'),
   faqs=[dict(q='双层网格怎么画？', a='用两个背景层分别画主/次格距。'+DIS)]),
 'identicon-generator': dict(
   summary='由字符串哈希生成对称的 identicon 方块头像，用作匿名标识。',
   scenarios=['匿名用户默认头像。',
              '账号占位图。',
              '演示哈希可视化。'],
   example=dict(title='由邮箱生成 identicon',
     body='<p><strong>输入：</strong>字符串 user@x.com。</p><p><strong>处理：</strong>哈希驱动 5×5 对称图案与配色。</p><p><strong>输出：</strong>identicon 图可下载。'+DIS+'</p>'),
   faqs=[dict(q='同输入同图吗？', a='是，确定性哈希；不同输入通常不同但不保证唯一。'+DIS)]),
 'image-color-picker': dict(
   summary='在上传图片上取色，显示该点 HEX/RGB 并可复制。',
   scenarios=['从参考图取准色。',
              '比对截图两处色。',
              '提取品牌色。'],
   example=dict(title='在截图取一处橙',
     body='<p><strong>输入：</strong>上传截图、点击橙色区。</p><p><strong>处理：</strong>读该像素颜色。</p><p><strong>输出：</strong>#FF6B35 等可复制。'+DIS+'</p>'),
   faqs=[dict(q='色准吗？', a='受显示屏与压缩影响，作近似参考。'+DIS)]),
 'image-compress': dict(
   summary='在浏览器本地压缩图片（调质量/尺寸），下载更小文件，不上传。',
   scenarios=['上传前压小图。',
              '邮件附件瘦身。',
              '网页图优化。'],
   example=dict(title='压 PNG 为 80% JPG',
     body='<p><strong>输入：</strong>2MB PNG、质量 80%。</p><p><strong>处理：</strong>canvas 重绘编码。</p><p><strong>输出：</strong>约 300KB 文件可下载，本地完成。'+DIS+'</p>'),
   faqs=[dict(q='会损质量吗？', a='有损压缩会降质换体积；需无损请用 PNG 并重定尺寸。'+DIS)]),
 'image-cropper': dict(
   summary='上传图片按框选比例裁剪，支持自由/固定比例，下载结果。',
   scenarios=['头像裁方形。',
              '封面按 16:9。',
              '去多余边。'],
   example=dict(title='裁 1:1 头像',
     body='<p><strong>输入：</strong>上传图、选 1:1 框。</p><p><strong>处理：</strong>裁剪画布区域。</p><p><strong>输出：</strong>方形图下载，本地处理。'+DIS+'</p>'),
   faqs=[dict(q='能旋转后裁吗？', a='先旋转再裁更准；本工具以框选裁剪为主。'+DIS)]),
 'image-dpi-converter': dict(
   summary='按目标 DPI 重设图片分辨率元数据与像素尺寸，用于打印准备。',
   scenarios=['网页图转打印 300DPI。',
              '确认输出尺寸。',
              '印刷前校尺寸。'],
   example=dict(title='设 300 DPI A4',
     body='<p><strong>输入：</strong>图 2480×3508、目标 300DPI。</p><p><strong>处理：</strong>换算物理尺寸。</p><p><strong>输出：</strong>A4 物理尺寸与重采样图。'+DIS+'</p>'),
   faqs=[dict(q='DPI 影响清晰吗？', a='DPI 决定打印尺寸下的像素密度；屏幕显示只看像素数。'+DIS)]),
 'image-flipper': dict(
   summary='水平/垂直翻转图片并下载，纯本地处理。',
   scenarios=['镜面自拍修正。',
              '对称构图。',
              '排版镜像。'],
   example=dict(title='水平翻转',
     body='<p><strong>输入：</strong>上传图、选水平。</p><p><strong>处理：</strong>canvas 翻转绘制。</p><p><strong>输出：</strong>翻转图下载。'+DIS+'</p>'),
   faqs=[dict(q='文字图翻转能读吗？', a='会镜像反写，文字图慎用水平翻转。'+DIS)]),
 'image-format-converter': dict(
   summary='在 PNG/JPEG/WEBP 等格式间转换并下载，本地编码。',
   scenarios=['PNG 转 JPG 压体积。',
              'WEBP 兼容回退。',
              '统一素材格式。'],
   example=dict(title='PNG 转 WEBP',
     body='<p><strong>输入：</strong>1MB PNG、目标 WEBP 质量 85。</p><p><strong>处理：</strong>canvas 重编码。</p><p><strong>输出：</strong>约 200KB WEBP 下载。'+DIS+'</p>'),
   faqs=[dict(q='WEBP 都支持吗？', a='现代浏览器支持；老旧环境需回退 JPG/PNG。'+DIS)]),
 'image-mosaic': dict(
   summary='用小图块拼出马赛克效果或像素化整图，可调块大小。',
   scenarios=['做像素风海报。',
              '隐私打码艺术化。',
              '头像像素化。'],
   example=dict(title='块 16px 像素化',
     body='<p><strong>输入：</strong>上传图、块 16px。</p><p><strong>处理：</strong>区域取平均色重绘。</p><p><strong>输出：</strong>马赛克图下载。'+DIS+'</p>'),
   faqs=[dict(q='块越大越糊？', a='是，块大即强像素化；按需取平衡。'+DIS)]),
 'image-resizer': dict(
   summary='按宽高或比例缩放图片，支持约束纵横比，本地重采样。',
   scenarios=['统一缩略图尺寸。',
              '社交封面定宽。',
              '减小文件。'],
   example=dict(title='缩到宽 800',
     body='<p><strong>输入：</strong>原 2400×1600、目标宽 800（锁比）。</p><p><strong>处理：</strong>等比重采样。</p><p><strong>输出：</strong>800×533 图下载。'+DIS+'</p>'),
   faqs=[dict(q='放大会糊吗？', a='放大靠插值，细节不会凭空出现，可能发虚。'+DIS)]),
 'image-rotator': dict(
   summary='按 90° 或任意角度旋转图片并下载，本地处理。',
   scenarios=['手机竖图转正。',
              '扫描件纠偏。',
              '构图旋转。'],
   example=dict(title='顺时针 90°',
     body='<p><strong>输入：</strong>上传横图、转 90°。</p><p><strong>处理：</strong>canvas 旋转重绘。</p><p><strong>输出：</strong>旋转图下载。'+DIS+'</p>'),
   faqs=[dict(q='任意角度留白？', a='非 90° 倍数会留透明/底色边，可裁掉。'+DIS)]),
 'image-rounded-corners': dict(
   summary='给图片加圆角并下载，支持四角独立。',
   scenarios=['头像圆角。',
              '卡片图圆角。',
              '统一图风格。'],
   example=dict(title='图圆角 16px',
     body='<p><strong>输入：</strong>上传图、四角 16px。</p><p><strong>处理：</strong>用 clip 路径裁剪。</p><p><strong>输出：</strong>圆角图下载。'+DIS+'</p>'),
   faqs=[dict(q='圆角图能透明吗？', a='可导出 PNG 保留透明边角。'+DIS)]),
 'image-to-ascii': dict(
   summary='将图片按亮度映射为 ASCII 字符画，可调分辨率与字符集。',
   scenarios=['做终端艺术。',
              '趣味头像。',
              '文档装饰。'],
   example=dict(title='生成 80 列 ASCII',
     body='<p><strong>输入：</strong>上传图、宽 80 列、字符集 @%#*+。</p><p><strong>处理：</strong>灰度映射字符。</p><p><strong>输出：</strong>可复制的字符画文本。'+DIS+'</p>'),
   faqs=[dict(q='为什么传出来是文本？', a='ASCII 画本质是字符文本，可直接粘到等宽环境。'+DIS)]),
 'image-to-base64': dict(
   summary='将图片转为 Base64 data URI，便于内联到 HTML/CSS。',
   scenarios=['小图内联减少请求。',
              '邮件嵌入图。',
              '调试内联资源。'],
   example=dict(title='转小图标为 data URI',
     body='<p><strong>输入：</strong>上传 4KB 图标。</p><p><strong>处理：</strong>读为 base64。</p><p><strong>输出：</strong>data:image/png;base64,… 可复制。'+DIS+'</p>'),
   faqs=[dict(q='大图也内联吗？', a='大图 base64 会膨胀约 33% 且不利缓存，建议仅小图内联。'+DIS)]),
 'image-watermark': dict(
   summary='给图片添加文字/图片水印，调位置透明度，下载。',
   scenarios=['作品加版权水印。',
              '内部素材标注。',
              '活动图打标。'],
   example=dict(title='右下角文字水印',
     body='<p><strong>输入：</strong>上传图、文字©TB、右下、透明 .3。</p><p><strong>处理：</strong>叠加绘制。</p><p><strong>输出：</strong>带水印图下载。'+DIS+'</p>'),
   faqs=[dict(q='能去掉吗？', a='水印为破坏性叠加，导出后难无损去除，请留原图。'+DIS)]),
 'initials-avatar': dict(
   summary='由姓名首字母生成头像图，调底色字色形状，下载。',
   scenarios=['成员默认头像。',
              '评论占位图。',
              '邮件头图。'],
   example=dict(title='"陈" 生成圆头像',
     body='<p><strong>输入：</strong>姓名陈、底 #7C3AED、白字、圆。</p><p><strong>处理：</strong>取首字绘制。</p><p><strong>输出：</strong>头像图下载。'+DIS+'</p>'),
   faqs=[dict(q='英文名取几个？', a='通常取首字母 1~2 个；中文多取末字或首字，按习惯。'+DIS)]),
 'iso-noise-reference': dict(
   summary='展示不同 ISO 档位对应的噪点参考样例，辅助摄影感度选择。',
   scenarios=['预判弱光噪点。',
              '教学 ISO 影响。',
              '选拍摄档位。'],
   example=dict(title='对比 ISO100/1600/6400',
     body='<p><strong>输入：</strong>选三档。</p><p><strong>处理：</strong>展示噪点样例。</p><p><strong>输出：</strong>噪点对比图，越高越粗。'+DIS+'</p>'),
   faqs=[dict(q='ISO 越高越亮？', a='是，但噪点增；优先用光圈/快门，最后提 ISO。'+DIS)]),
 'isometric-grid': dict(
   summary='生成等距（2.5D）网格背景，用于插画/示意图底。',
   scenarios=['等距插画底。',
              '架构示意图。',
              '游戏地图。'],
   example=dict(title='生成等距格',
     body='<p><strong>输入：</strong>格距、线色。</p><p><strong>处理：</strong>菱形网格平铺。</p><p><strong>输出：</strong>背景预览与代码/图。'+DIS+'</p>'),
   faqs=[dict(q='等距和正交？', a='等距呈 30° 菱形，更有立体感；正交为正方格。'+DIS)]),
 'loading-dots': dict(
   summary='生成三点跳动加载动画 CSS，可调色与速度。',
   scenarios=['按钮提交等待。',
              '列表加载。',
              '骨架占位配合。'],
   example=dict(title='生成橙点跳动',
     body='<p><strong>输入：</strong>3 点、色 #FF6B35、0.6s。</p><p><strong>处理：</strong>生成 keyframes。</p><p><strong>输出：</strong>预览与 CSS。'+DIS+'</p>'),
   faqs=[dict(q='能换形状吗？', a='本工具为圆点；方块/条可用 spinner 类工具。'+DIS)]),
 'material-color': dict(
   summary='展示 Material Design 配色与明度档，复制色值。',
   scenarios=['用 Material 规范配色。',
              '取 primary/surface。',
              '对齐设计系统。'],
   example=dict(title='浏览 Primary 色阶',
     body='<p><strong>输入：</strong>选 Primary 色。</p><p><strong>处理：</strong>列 50~900。</p><p><strong>输出：</strong>色块与 HEX 可复制。'+DIS+'</p>'),
   faqs=[dict(q='和 Tailwind 一样吗？', a='档位概念类似但数值不同，按所用体系取。'+DIS)]),
 'mesh-gradient': dict(
   summary='生成多色网格渐变（mesh），调控制点与颜色，导出 CSS/SVG。',
   scenarios=['现代海报背景。',
              '品牌渐变。',
              'Web 玻璃层。'],
   example=dict(title='生成三色 mesh',
     body='<p><strong>输入：</strong>橙/紫/青三控制点。</p><p><strong>处理：</strong>径向叠加成 mesh。</p><p><strong>输出：</strong>预览与 CSS/SVG。'+DIS+'</p>'),
   faqs=[dict(q='mesh 和线性渐变？', a='mesh 多点非线性过渡更自然，常用于大背景。'+DIS)]),
}

miss = [k for k in DATA if ('design/'+k) not in d]
assert not miss, '以下 key 不在 content_deepdive: %s'%miss
extra = [k for k in d if k.startswith('design/') and k.split('/')[1] in DATA]
for k,v in DATA.items():
    key='design/'+k
    d[key]['summary']=v['summary']
    d[key]['scenarios']=v['scenarios']
    d[key]['examples']=[v['example']]
    d[key]['faqs']=v['faqs']
json.dump(d, open(P,'w',encoding='utf-8'), ensure_ascii=False, indent=2)
print('design a 批已写入 %d key'%len(DATA))
# 校验字段
bad=[k for k,v in DATA.items() if not (v['summary'] and len(v['scenarios'])==3 and len(v['faqs'])==3 and 'body' in v['example'])]
print('字段异常:', bad)
