#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
工具描述补充表：按工具中文名索引 -> (中文描述, 英文描述)

背景：分类导航/首页分类主体的工具卡片第二行需要一句话说明，但部分工具的
源数据里 meta description 就等于工具名（等于没写），而 tools.json 的 ed 字段
92% 是「Free online tool on ToolBox」模板套话（见 gen_industry_groups.en_desc）。

对这批"确实没有描述"的工具，这里人工补齐中英文各一句，宁可简短也不要套话。
key 用中文名（与 gen_industry_groups.zh_name() 的输出保持一致）。
"""

DESC_OVERRIDE = {
    # ---- IT / 编码 ----
    '仿射密码 (Affine Cipher)': ('按 y=(ax+b) mod 26 加密解密',
                              'Encrypt and decrypt with y = (a·x + b) mod 26'),
    'ASCII 大字生成器': ('把文字转成 ASCII 艺术大字',
                    'Turn text into large ASCII art banners'),
    'ASCII 字符表': ('查询 ASCII 码与对应字符',
                 'Look up ASCII codes and their characters'),
    'Base64 转图片': ('把 Base64 字符串还原成图片',
                  'Turn a Base64 string back into an image'),
    'Aztec 码 (简化版)': ('生成简化版 Aztec 二维码',
                      'Generate a simplified Aztec code'),
    'Pharmacode 条形码': ('生成药品 Pharmacode 条码',
                      'Generate a Pharmacode barcode'),
    '条形码/二维码数据生成（已有）': ('生成条码与二维码的数据内容',
                            'Generate data content for barcodes and QR codes'),
    '装饰文字（Fancy Text）': ('把文字转成花体装饰样式',
                        'Convert text into fancy decorative styles'),
    '音频采样率转换（kHz）': ('换算音频采样率与时长',
                      'Convert audio sample rate and duration'),
    '3D 渲染时间估算': ('按场景复杂度估算渲染耗时',
                  'Estimate render time from scene complexity'),

    # ---- 电子 / 通信 ----
    '运放增益带宽设计': ('计算运放增益带宽积与带宽',
                  'Compute op-amp gain-bandwidth product and bandwidth'),
    'RC充放电时间常数': ('算 RC 电路时间常数与充放电过程',
                   'Compute RC time constant and charge/discharge curve'),
    '晶振负载电容匹配': ('匹配晶振负载电容取值',
                  'Match the load capacitance of a crystal'),
    '误码率（BER）与信噪比换算': ('换算误码率与信噪比关系',
                        'Convert between bit error rate and SNR'),
    '带宽下载时间速算': ('按带宽估算文件下载耗时',
                  'Estimate download time from bandwidth and file size'),
    '带宽（Mbps）与下载时间速算': ('按 Mbps 带宽估算下载时间',
                         'Estimate download time from Mbps bandwidth'),
    '频谱分析（可视化）': ('可视化信号的频谱分布',
                   'Visualize the frequency spectrum of a signal'),
    '防蓝光透射比计算器': ('计算镜片防蓝光透射比',
                   'Compute blue-light transmittance of a lens'),

    # ---- 生活 / 设计 ----
    '防晒系数SPF/PA计算': ('估算 SPF 与 PA 防护时长',
                     'Estimate SPF and PA protection duration'),
    '花艺黄金比例计算器': ('按黄金比例设计花艺尺寸',
                   'Design floral arrangements with the golden ratio'),
    '乳胶漆调色计算器': ('按目标色计算乳胶漆配比',
                  'Compute latex paint mixing ratios by target color'),
    '踢脚线长度计算器': ('按房间周长算踢脚线用量',
                  'Compute skirting length from room perimeter'),
    '纸箱外箱尺寸计算': ('由内装物推算外箱尺寸',
                  'Derive carton size from its contents'),
    '缓冲材料厚度计算': ('按跌落条件算缓冲垫厚度',
                  'Size cushioning thickness for drop protection'),

    # ---- 金融 / 商业 ----
    '印度 Aadhaar 验证': ('校验印度 Aadhaar 号码',
                    'Validate an Indian Aadhaar number'),
    'ABA 路由号码验证': ('校验美国 ABA 路由号码',
                   'Validate a US ABA routing number'),
    '澳大利亚 ABN 验证': ('校验澳大利亚 ABN 商号',
                    'Validate an Australian ABN'),
    '资本利得税计算器': ('计算资本利得应缴税额',
                  'Compute capital gains tax'),
    '交叉价格弹性计算器': ('计算两种商品的交叉价格弹性',
                   'Compute cross-price elasticity between two goods'),
    '连续复利终值计算器': ('按连续复利计算终值',
                   'Compute future value with continuous compounding'),
    '质量（标准/检查/提升）体系': ('梳理质量标准、检查与提升项',
                        'Map quality standards, checks and improvements'),
    '活动（策划/执行/评估）方案': ('生成活动策划、执行与评估方案',
                        'Draft an event plan with execution and review'),
    '户外（广告/投放/评估）方法': ('规划户外广告投放与效果评估',
                        'Plan outdoor ads and evaluate their reach'),
    '风险（预警/评估/应对）模型': ('建立风险预警、评估与应对模型',
                        'Build a risk warning, assessment and response model'),
    '退货逆向物流流程检查': ('检查退货逆向物流各环节',
                    'Audit each step of the reverse-logistics return flow'),
    '出租率与 RevPAR 计算': ('算出租率与每间可售房收入',
                      'Compute occupancy rate and RevPAR'),
    '客户满意度（CSAT）评分汇总': ('汇总 CSAT 满意度评分',
                        'Summarize CSAT satisfaction scores'),
    '舆情情感倾向简单分析（词频）': ('用词频粗略判断舆情倾向',
                          'Roughly gauge sentiment from word frequency'),
    '公关（效果/评估/报告）体系': ('搭建公关效果评估与报告框架',
                        'Build a PR evaluation and reporting framework'),
    '保密管理合规自查': ('自查保密管理合规要点',
                  'Self-check confidentiality compliance'),
    '风险（辨识/评估/应对）循环': ('走完风险辨识、评估与应对循环',
                        'Run the risk identification-assessment-response loop'),
    '品质（检查/标准/整改）体系': ('梳理品质检查标准与整改项',
                        'Map quality checks, standards and corrective actions'),

    # ---- 健康医疗 ----
    '基础代谢率 BMR': ('按性别年龄体重算基础代谢',
                  'Compute BMR from sex, age and weight'),
    '核心（稳定性）评估': ('评估核心肌群稳定性水平',
                   'Assess core stability level'),
    '避孕（Pearl指数）失败率': ('用 Pearl 指数估算避孕失败率',
                        'Estimate contraceptive failure rate (Pearl index)'),
    '产后出血（预估失血量）计算': ('估算产后出血量与风险',
                        'Estimate postpartum blood loss'),
    '桥体跨度（缺牙区间）力学分析': ('分析缺牙区桥体跨度的受力',
                          'Analyze bridge span mechanics for missing teeth'),
    '附睾穿刺精子获取率评估器': ('评估附睾穿刺取精成功率',
                       'Estimate sperm retrieval rate from epididymal aspiration'),
    '眼部A超(眼轴长度)计算器': ('按 A 超数据计算眼轴长度',
                        'Compute axial eye length from A-scan data'),
    '角膜曲率(K1/K2)与散光计算器': ('由 K1/K2 计算角膜散光',
                          'Compute corneal astigmatism from K1/K2'),
    '喉返神经（麻痹）声学分析': ('分析声学指标判断神经麻痹',
                        'Analyze voice acoustics for nerve palsy'),
    '前庭功能(冷热试验)半规管评估器': ('用冷热试验评估半规管功能',
                           'Evaluate semicircular canals with caloric testing'),
    '手术体位（压力点）风险评估': ('评估手术体位压疮风险点',
                        'Assess pressure-point risk for surgical positioning'),
    '心脏康复(METs)等价换算器': ('把运动强度换算成 METs 值',
                        'Convert exercise intensity into METs'),
    '哮喘（GINA控制）评估': ('按 GINA 标准评估哮喘控制',
                      'Rate asthma control using GINA criteria'),
    '电泳图谱（血清蛋白）区带分析': ('分析血清蛋白电泳区带比例',
                          'Analyze serum protein electrophoresis bands'),
    '膀胱容量(残余尿+尿量)测量器': ('由残余尿与尿量算膀胱容量',
                          'Compute bladder capacity from residual and voided volume'),
    '导尿管(型号/球囊)选择器': ('按需求选导尿管型号与球囊',
                        'Pick catheter size and balloon volume'),
    '强直性脊柱炎 BASDAI 疾病活动评估器': ('用 BASDAI 评估病情活动度',
                              'Score disease activity with BASDAI'),
    '方剂君臣佐使（剂量比例）分析': ('分析方剂君臣佐使配伍比例',
                          'Analyze monarch-minister-assistant-courier ratios'),
    '方歌（七言绝句）生成器': ('生成七言绝句体方剂歌诀',
                      'Generate a seven-character quatrain formula song'),
    '脂溢性皮炎（头皮屑）评估': ('评估脂溢性皮炎与头屑程度',
                        'Grade seborrheic dermatitis and dandruff'),
    '湿疹(EASI)面积强度评估器': ('用 EASI 评分评估湿疹严重度',
                         'Score eczema severity with EASI'),
    '痤疮(GAGS)分级器': ('按 GAGS 标准给痤疮分级',
                    'Grade acne using the GAGS scale'),
    '肠化生（萎缩范围）评估': ('评估肠化生与萎缩范围',
                      'Assess intestinal metaplasia and atrophy extent'),
    '胆红素（直接/间接）比值计算器': ('由直接间接胆红素算比值判病因',
                          'Compute the direct/indirect bilirubin ratio'),
    '幽门螺杆菌（抗生素）耐药检测': ('判断幽门螺杆菌抗生素耐药性',
                          'Check H. pylori antibiotic resistance'),
    '拔罐印色（病理）分析': ('按罐印颜色分析病理提示',
                     'Interpret cupping mark colors'),
    '毒性剂量（LD50）换算': ('按体重换算 LD50 毒性剂量',
                      'Convert LD50 dose by body weight'),
    'HOMA-IR 胰岛素抵抗指数': ('由血糖与胰岛素算 HOMA-IR',
                        'Compute HOMA-IR from glucose and insulin'),
    '高坠（损伤分布）重力分析': ('分析高处坠落冲击与损伤分布',
                       'Analyze fall impact forces and injury distribution'),
    '问诊（十问歌）自动生成问卷': ('按十问歌生成中医问诊问卷',
                        'Generate a TCM intake questionnaire from the ten questions'),
    '添加剂（摄入评估）安全量': ('评估食品添加剂摄入是否超标',
                       'Check additive intake against safety limits'),
    '性格色彩分析（四色模型）': ('按四色模型分析性格倾向',
                       'Analyze personality with the four-color model'),
    '认知偏差卡片（随机展示）': ('随机抽取认知偏差卡片学习',
                       'Draw random cognitive-bias cards'),
    '血型性格分析（内置描述）': ('按血型查看性格倾向描述',
                       'Read personality descriptions by blood type'),

    # ---- 工程 / 材料 ----
    '多光谱（NDVI）分析': ('计算多光谱 NDVI 植被指数',
                    'Compute NDVI from multispectral bands'),
    '抗风（等级）性能评估': ('评估结构抗风等级与风压',
                    'Assess wind resistance rating and wind pressure'),
    '防洪（设计洪水）频率分析': ('分析设计洪水重现期与频率',
                       'Analyze design flood frequency and return period'),
    '齐奥尔科夫斯基公式': ('用火箭方程算速度增量',
                   'Compute delta-v with the Tsiolkovsky rocket equation'),
    '消防设施合规性自查': ('按规范自查消防设施配置',
                   'Self-check fire facilities against code'),
    '混凝土配合比计算（土木）': ('计算混凝土各材料配合比',
                       'Compute concrete mix proportions'),
    '电流分流器计算（电气）': ('计算分流器电阻与量程',
                      'Size a current shunt resistor and range'),
    '事故频率 / 严重率统计报表': ('统计事故频率与严重率指标',
                         'Report accident frequency and severity rates'),
    '轴向拉压应力与应变计算（工程）': ('计算轴向拉压的应力与应变',
                           'Compute axial stress and strain'),
    '梁受弯最大弯曲应力计算（工程）': ('算梁受弯时的最大弯曲应力',
                           'Compute max bending stress in a beam'),
    '螺栓预紧力计算（工程）': ('由扭矩推算螺栓预紧力',
                      'Compute bolt preload from torque'),
    '悬臂梁端部集中荷载挠度（工程）': ('算悬臂梁端部集中荷载挠度',
                           'Compute cantilever tip deflection under point load'),
    '泊松比横向应变计算（工程）': ('由泊松比计算横向应变',
                         'Compute lateral strain from Poisson ratio'),
    '简支梁跨中集中力计算（机械）': ('算简支梁跨中集中力响应',
                          'Compute mid-span response of a simply supported beam'),
    '皮带传动计算（机械）': ('计算皮带传动比与长度',
                     'Compute belt drive ratio and length'),
    '离心力计算（机械）': ('按转速与半径计算离心力',
                    'Compute centrifugal force from speed and radius'),
    '缓冲区（半径）分析': ('按要素生成缓冲区半径分析',
                   'Analyze buffer radius around features'),
    'GPS（精度/PDOP）评估': ('评估 GPS 定位精度与 PDOP',
                      'Assess GPS accuracy and PDOP'),
    '坐标（经纬度）与度分秒转换': ('十进制度与度分秒互转',
                         'Convert decimal degrees to DMS and back'),
    '质量（标准/检测/认证）保障': ('梳理标准、检测与认证要求',
                         'Map standards, testing and certification needs'),
    '酸碱中和滴定计算器': ('计算酸碱中和滴定结果',
                   'Compute acid-base titration results'),
    '皮革（面积重量）换算': ('皮革面积与重量互算',
                    'Convert leather area and weight'),
    '矿石品位（克/吨）与价值换算': ('由品位克吨换算矿石价值',
                         'Convert ore grade (g/t) into value'),
    '色差 ΔE(CMC) 评估': ('用 CMC 公式评估色差 ΔE',
                     'Evaluate color difference ΔE with CMC'),
    '纸张克重（gsm）与厚度换算': ('克重与纸张厚度互算',
                         'Convert paper gsm and thickness'),
    '管道压降计算（达西公式）': ('用达西公式算管道压降',
                       'Compute pipe pressure drop with Darcy-Weisbach'),
    '储罐容量与液位换算': ('储罐液位与容积互算',
                   'Convert tank level to volume'),
    '橡胶拉伸强度计算': ('计算橡胶拉伸强度指标',
                  'Compute rubber tensile strength'),
    '注塑成型周期计算': ('估算注塑成型周期时间',
                  'Estimate injection molding cycle time'),
    '汽车百公里加速时间估算': ('由功率与车重估算加速时间',
                      'Estimate 0-100 km/h time from power and weight'),
    '轮胎尺寸升级计算器': ('对比升级轮胎规格与误差',
                   'Compare upgraded tire sizes and deviation'),
    '上偏差 − 下偏差': ('计算尺寸上下偏差与公差',
                  'Compute upper/lower deviation and tolerance'),
    '伯努利压力计算器': ('用伯努利方程算流体压力',
                  'Compute fluid pressure with Bernoulli equation'),
    '连续性方程计算器': ('用连续性方程算流速流量',
                  'Compute flow rate with the continuity equation'),
    '由初态求末态角速度': ('由初始角速度求末态角速度',
                   'Find final angular velocity from the initial state'),

    # ---- 科学 ----
    '单因素方差分析（ANOVA）': ('做单因素方差分析检验差异',
                       'Run one-way ANOVA to test group differences'),
    '贝叶斯定理计算器': ('用贝叶斯公式算后验概率',
                  'Compute posterior probability with Bayes theorem'),
    '潮汐（天文）调和分析': ('做天文潮汐调和分析',
                    'Run astronomical tide harmonic analysis'),
    '玻尔轨道半径计算器': ('计算玻尔模型轨道半径',
                   'Compute Bohr model orbital radius'),
    '玻意耳定律计算器': ('用玻意耳定律算压强体积',
                  'Apply Boyle law to pressure and volume'),
    '查尔斯定律计算器': ('用查尔斯定律算体积温度',
                  'Apply Charles law to volume and temperature'),
    '原子核结合能计算器': ('计算结合能与质量亏损',
                   'Compute nuclear binding energy and mass defect'),
    '射击（弹着点）散布分析': ('分析弹着点散布与精度',
                      'Analyze shot dispersion and accuracy'),
    '空气质量指数（AQI）类别换算': ('污染物浓度与 AQI 类别互算',
                          'Convert pollutant concentration to AQI category'),

    # ---- 食品 / 农业 ----
    '农机具作业效率对比': ('对比不同农机作业效率',
                   'Compare field efficiency of farm machines'),
    '酸价/过氧化值（油脂）滴定换算': ('换算油脂酸价与过氧化值',
                           'Convert oil acid value and peroxide value'),
    '蛋白质（凯氏定氮）系数换算': ('用凯氏定氮系数换算蛋白质',
                         'Convert nitrogen to protein with the Kjeldahl factor'),
    '红酒酒精度换算（比重法）': ('由比重换算红酒酒精度',
                       'Convert wine alcohol content from specific gravity'),
    '面团吸水率与最终水分含量计算器': ('算面团吸水率与最终水分',
                            'Compute dough water absorption and final moisture'),
    '乳化稳定性（离心分层）测试器': ('测乳化体系离心分层情况',
                          'Test emulsion stability by centrifugal separation'),
    '包装残氧量（顶空分析）估算': ('估算包装顶空残氧量',
                         'Estimate headspace residual oxygen in a package'),
    '发酵罐糖度（Brix）与酒精转化计算器': ('由糖度 Brix 估算酒精产量',
                              'Estimate alcohol yield from Brix'),
    '面团含水量计算器': ('计算面团含水量百分比',
                  'Compute dough hydration percentage'),
    '液肥稀释ppm计算器': ('算液肥稀释到目标 ppm',
                    'Dilute liquid fertilizer to a target ppm'),
    '食品（追溯）编码生成': ('生成食品追溯批次编码',
                    'Generate a food traceability batch code'),
    '重金属（限量）汇总': ('汇总食品重金属限量标准',
                   'Summarize heavy-metal limits for food'),

    # ---- 生活 / 教育 / 其他 ----
    '宠物年龄（猫/狗）与人类换算': ('猫狗年龄换算成人类年龄',
                         'Convert cat and dog age to human years'),
    '宠物每日喂食量计算器': ('按体重算宠物每日喂食量',
                     'Compute daily pet food portion from weight'),
    '快递保价费计算器': ('按声明价值算保价费用',
                  'Compute insured-value shipping fee'),
    '保洁质量检查与考核评分': ('按标准给保洁质量打分',
                      'Score cleaning quality against a checklist'),
    '保洁流程标准化评估': ('评估保洁流程标准化程度',
                    'Assess how standardized a cleaning process is'),
    '考试成绩目标计算': ('算达到目标分所需得分',
                  'Compute the score needed to hit a target'),
    '战术（攻防）视频分析': ('拆解比赛攻防战术片段',
                    'Break down attacking and defensive plays on video'),
    '打字节奏感测试（拍子分析）': ('测打字节奏稳定性与拍子',
                         'Test typing rhythm and timing consistency'),
    '学员满意度与进步评估': ('评估学员满意度与进步幅度',
                     'Evaluate learner satisfaction and progress'),
    'Elo等级分估算': ('按对局结果估算 Elo 等级分',
                  'Estimate Elo rating from match results'),

    # ===== 第二批：英文描述补齐（中文多为套话或缺失，一并重写）=====
    'A1Z26 密码': ('用 A=1…Z=26 的数字替换字母',
              'Substitute letters with alphabet positions (A=1 … Z=26)'),
    'ADFGVX 密码': ('一战德军密码，6×6 方阵加列置换',
               'WWI German cipher: 6×6 grid plus column transposition'),
    'AES 加密 / 解密': ('AES-128/192/256 加解密，支持 ECB/CBC/CFB',
                  'AES-128/192/256 encryption and decryption (ECB/CBC/CFB)'),
    'API 签名生成器': ('生成带时间戳与随机数的接口签名',
                 'Build API signatures with timestamps and nonces'),
    '美国区号查询': ('查询美国电话区号所属地区',
               'Look up the US region an area code belongs to'),
    '图像卷积输出尺寸': ('算卷积或池化后的特征图尺寸',
                 'Compute feature map size after convolution or pooling'),
    '过拟合诊断': ('按训练与验证损失判断过拟合',
             'Spot overfitting from training vs validation loss'),
    '数据增强有效量': ('估算数据增强后的等效样本量',
                'Estimate the effective sample size after augmentation'),
    '早停耐心估算': ('按训练速度估算早停耐心值与耗时',
               'Estimate early-stopping patience and total training time'),
    '词嵌入余弦检索': ('按余弦相似度给文档排序',
                'Rank documents by cosine similarity to a query'),
    '贝叶斯后验概率': ('由先验与似然计算后验概率',
                'Compute posterior probability from prior and likelihood'),
    '模型融合加权投票': ('多模型加权投票得出集成概率',
                 'Blend several models with weighted voting'),
    '提示词上下文窗口': ('计算多轮对话占用的上下文比例',
                 'Measure how much context multi-turn chat consumes'),
    'ASCII 可读性检测': ('估算文本中可打印字符的占比',
                  'Estimate the share of printable ASCII characters'),
    'Base32 编码长度': ('计算 Base32 编码长度并与 Base64 对比',
                  'Compute Base32 length and compare it with Base64'),
    'Base32 编码长度估算': ('按字节数估算 Base32 编码后长度',
                    'Estimate Base32 string length from input bytes'),
    'Base58 校验长度': ('估算含 4 字节校验的 Base58 长度',
                  'Estimate Base58 length including its 4-byte checksum'),
    'Base64 编码长度': ('计算字节数据编码后的字符数',
                  'Count the Base64 characters produced from raw bytes'),
    'Base64 编码大小': ('按原始大小估算编码后体积',
                  'Estimate encoded size from the original data size'),
    'Base64 编码 / 解码': ('Base64 与 Base64Url 编解码',
                     'Encode and decode both Base64 and Base64Url'),
    '电感感抗频率': ('由电感量与频率计算感抗',
              'Compute inductive reactance from inductance and frequency'),
    '电容计算器': ('电容串并联、充放电与 RC 时间常数',
             'Series, parallel, charge/discharge and RC time constant'),
    '电路分析计算': ('RLC 谐振、功率、分贝与电抗',
              'RLC resonance, power, decibel and reactance'),
    '电容（代码/耐压）换算': ('换算电容标称代码与耐压值',
                    'Convert capacitor code markings and voltage ratings'),
    'CSV 分析器': ('解析 CSV 并统计每列信息',
             'Parse a CSV file and summarize each column'),
    '数据清洗': ('去重、去空并格式化文本或 CSV',
           'Clean text or CSV: dedupe, drop blanks, reformat'),
    '数据可视化': ('绘制直方图、箱线图与热力图',
            'Draw histograms, box plots and heatmaps'),
    '假数据生成（姓名、电话、邮箱、地址、公司）': ('批量生成姓名、电话、邮箱等测试数据',
                              'Generate fake names, phones, emails and addresses'),
    '关键词密度分析': ('统计关键词出现次数与密度',
                'Count keyword frequency and density in a text'),
    '大小写转换（小写/大写/首字母大写）': ('在小写、大写与首字母大写间转换',
                          'Switch between lower case, upper case and title case'),
    '驼峰/下划线/短横线互转': ('驼峰、下划线与短横线命名互转',
                     'Convert camelCase, snake_case and kebab-case'),
    '敏感词检测器': ('检测并标记文本中的敏感词',
              'Detect and flag sensitive words in text'),
    '字数统计（含字符数、单词数）': ('统计字符数、单词数与行数',
                       'Count characters, words and lines'),
    '防诈骗知识卡片': ('浏览常见诈骗手法与识别要点',
                'Browse common scam patterns and how to spot them'),
    '数据销毁模拟器': ('可视化常见数据擦除算法的步骤',
                'Visualize how common data-erasure algorithms work'),
    '质量（标准/认证/检测）保障': ('按标准判定安防产品防护等级',
                        'Grade security products against national standards'),
    '地震逃生路线规划': ('按居住环境生成地震逃生建议',
                 'Get earthquake escape advice tailored to your home'),
    '紧急联系人面板': ('查看常用紧急电话并添加自定义联系人',
                'Keep emergency numbers plus your own contacts'),
    '急救包清单生成器': ('按场景生成急救物品清单',
                 'Build a first-aid checklist for your scenario'),
    '洪水水位标尺': ('对照洪水预警等级与应对举措',
              'Compare flood warning levels and what to do'),
    '端口扫描器模拟': ('模拟端口扫描并查看常见端口风险',
                'Simulate a port scan and review common port risks'),
    'AP覆盖半径': ('估算无线 AP 的信号覆盖半径',
             'Estimate the coverage radius of a wireless AP'),
    '误码率信噪比换算': ('数字调制下 BER 与 Eb/N0 互算',
                 'Convert between BER and Eb/N0 for digital modulation'),
    '自由空间路径损耗估算': ('用 Friis 方程算自由空间损耗',
                   'Compute free-space path loss with the Friis equation'),
    '路径损耗估算': ('估算无线信号传输损耗与接收强度',
              'Estimate wireless path loss and received signal strength'),
    '子网划分工具': ('把网络划分为多个等长子网',
              'Split a network into equal-sized subnets'),
    'Excel 公式速查表': ('速查常用 Excel 函数与语法',
                  'Look up common Excel functions and syntax'),
    'Markdown 编辑器（分屏预览）': ('左侧编辑右侧实时预览 Markdown',
                         'Edit Markdown on the left, preview live on the right'),
    '思维导图编辑器': ('用缩进文本实时生成思维导图',
                'Turn indented text into a live mind map'),
    'PDF合并工具': ('按顺序合并多个 PDF 文件',
              'Merge several PDFs in the order you choose'),
    'PDF页面旋转工具': ('旋转 PDF 单页或全部页面',
                 'Rotate single pages or every page of a PDF'),
    'PDF 拆分工具': ('按页码范围拆分 PDF 文件',
               'Split a PDF by page ranges'),
    '效果（监测/分析/优化）模型': ('按监测、分析与优化三步梳理效果',
                        'Structure effects into monitor, analyze, optimize'),
    '工具（分析/管理/监测）使用': ('覆盖分析、管理与监测环节',
                        'Cover the analysis, management and monitoring loop'),
    '子网掩码计算（CIDR / 子网划分）': ('由 IP 与 CIDR 算子网掩码与范围',
                           'Compute subnet mask and range from IP and CIDR'),
    'IP地址转换（十进制 ↔ 二进制）': ('IP 地址十进制与二进制互转',
                          'Convert IP addresses between decimal and binary'),
    '功耗（动态/静态）分析': ('分析电路动态与静态功耗',
                     'Analyze dynamic and static power consumption'),
    '调色板提取（从图片上传，Canvas分析）': ('从图片中提取主色调色板',
                              'Extract a dominant color palette from an image'),
    '音频录制处理器': ('录制音频并调节音量与速度',
                'Record audio, adjust volume and speed, view the waveform'),
    '头像生成器': ('生成风格统一的占位头像',
             'Generate placeholder avatars in a consistent style'),

    # ===== 第三批：清除中文描述里的模板套话（"纯前端运行/数据不上传"之类）=====
    'JSON格式化': ('格式化、压缩并校验 JSON 数据',
              'Format, validate and minify JSON data'),
    '流程图绘制工具': ('用 Mermaid 语法绘制流程图',
                'Draw flowcharts with Mermaid syntax'),
    '徽章生成器': ('生成扁平风格的徽章图标',
             'Generate badge icons in a flat vector style'),
    '蓝图网格': ('生成可打印的蓝图网格背景',
           'Create printable blueprint grid backgrounds'),
    '圆角生成器': ('预览并复制 CSS 圆角代码',
             'Preview and copy CSS border-radius code'),
    '竞品（份额/定位）分析': ('对比竞品市场份额与定位',
                    'Compare competitor market share and positioning'),
    '证件照裁剪器': ('按规格裁剪并排版证件照',
              'Crop and lay out ID photos to spec'),
    '舆情（情感/词频）分析': ('用词频与情感判断舆情倾向',
                    'Gauge sentiment and word frequency in public opinion'),
    '数字大写转换器': ('把金额转成中文大写数字',
               'Convert amounts into Chinese capital numerals'),
    '欧式看涨期权定价': ('用 Black-Scholes 算看涨期权价',
                 'Price a European call with Black-Scholes'),
    '欧式看跌期权定价': ('用 Black-Scholes 算看跌期权价',
                 'Price a European put with Black-Scholes'),
    '视野缺损（MD/PSD）分析': ('分析视野 MD 与 PSD 指标',
                      'Interpret visual field MD and PSD indices'),
    '视力表（Snellen/logMAR）换算': ('Snellen 与 logMAR 视力值互转',
                          'Convert between Snellen and logMAR acuity'),
    '血气分析（pH/PaO2/PaCO2）代偿判断': ('判断酸碱失衡与代偿情况',
                              'Judge acid-base imbalance and compensation'),
    '步态分析（支撑相/摆动相）时间比': ('分析步态支撑相与摆动相占比',
                            'Analyze stance and swing phase ratios'),
    '血糖单位换算（mmol/L ↔ mg/dL）': ('mmol/L 与 mg/dL 血糖值互转',
                            'Convert blood glucose between mmol/L and mg/dL'),
    '静脉输液滴速与时间换算（已有但加强）': ('由滴速与总量算输液时长',
                              'Compute infusion time from drip rate and volume'),
    '养老护理等级速查': ('速查养老护理等级评定标准',
                 'Look up eldercare assessment levels'),
    '多边形闭合面积': ('按顶点坐标算闭合多边形面积',
                'Compute the area of a polygon from its vertices'),
    '布雷盖航程': ('用布雷盖公式估算航程',
             'Estimate range with the Breguet equation'),
    '安全日志分析器（本地导入日志）': ('导入日志并定位异常与告警',
                          'Import logs and surface anomalies and alerts'),
    '轴承寿命估算': ('按载荷与转速估算轴承寿命',
              'Estimate bearing life from load and speed'),
    '坡度（百分比/角度）换算': ('坡度百分比与角度互算',
                     'Convert slope between percent and degrees'),
    '沸点升高计算器': ('按溶质浓度算沸点升高值',
                'Compute boiling point elevation from concentration'),
    '灯箱亮度（cd/m²）均匀度分析': ('分析灯箱亮度与均匀度',
                         'Analyze light box luminance and uniformity'),
    '燃油效率单位转换（MPG ↔ L/100km）': ('MPG 与 L/100km 油耗互转',
                             'Convert fuel economy between MPG and L/100km'),
    '快递运费计算器': ('按重量与区域算快递运费',
                'Compute shipping cost from weight and zone'),
    '包装材积计算器': ('算包装体积与抛重',
                'Compute package volume and volumetric weight'),
    '路线坡度（百分比与角度）互转': ('路线坡度百分比与角度互算',
                        'Convert route gradient between percent and degrees'),
    '航速（对水/对地）换算': ('对水航速与对地航速互算',
                     'Convert speed through water and over ground'),
    '标准器 + 重复性': ('评定标准器与重复性不确定度',
                  'Evaluate standard and repeatability uncertainty'),
    '角加速度计算器': ('由角速度变化算角加速度',
                'Compute angular acceleration from velocity change'),
    '比结合能计算器': ('计算原子核的比结合能',
                'Compute binding energy per nucleon'),
    '地震震级与能量换算（里氏↔焦耳）': ('里氏震级与释放能量互算',
                           'Convert Richter magnitude to released energy'),
    '时区转换（内置全球时区）': ('在全球时区之间换算时间',
                       'Convert times across world time zones'),
    '大气压与海拔转换（气压计读数）': ('由气压读数估算海拔高度',
                          'Estimate altitude from barometric pressure'),
    '口径（毫米/英寸）换算': ('毫米与英寸口径互算',
                     'Convert caliber between millimeters and inches'),
    '幻方生成器': ('生成任意阶数的幻方',
             'Generate magic squares of any order'),
    '置信区间计算': ('按样本计算均值的置信区间',
              'Compute a confidence interval for the mean'),
    '进制转换': ('二、八、十、十六进制互转',
           'Convert between binary, octal, decimal and hex'),
    '蛋鸡（产蛋率/料蛋比）分析': ('分析产蛋率与料蛋比指标',
                       'Analyze laying rate and feed-to-egg ratio'),
    '瞄准训练': ('练习鼠标瞄准速度与精度',
           'Train mouse aiming speed and precision'),
    '视频帧率转换（fps换算）': ('换算视频帧率与时长',
                      'Convert video frame rate and duration'),
    '宠物年龄换算': ('猫狗年龄换算成人类年龄',
              'Convert pet age into human years'),
    '烘焙百分比（面粉为100%）配料换算': ('按烘焙百分比换算配料用量',
                            'Scale ingredients using baker percentages'),
    '烤箱温度（摄氏度/华氏度）转换与风温补偿': ('烤箱摄氏华氏互转并做风温补偿',
                                'Convert oven temperature and adjust for convection'),
    '菜品定价计算器': ('按成本与目标毛利率定价',
                'Price a dish from cost and target margin'),
    '家具布局规划': ('在平面上规划家具摆放',
              'Plan furniture placement on a floor plan'),
    '照明计算': ('按房间面积算所需照明功率',
           'Size lighting needs from room area'),
    '24 点求解器': ('求解 24 点的算式组合',
              'Find solutions to the 24-point card game'),
    '首都测验': ('测验世界各国首都知识',
           'Quiz yourself on world capitals'),
    '颜色测验': ('测验对颜色的辨识能力',
           'Test how well you distinguish colors'),
    '偏旁部首查询': ('查询汉字的偏旁与部首',
              'Look up Chinese character radicals'),
    '笔画笔顺演示': ('演示汉字笔画与书写顺序',
              'Show stroke count and writing order'),
    '参考文献著录格式转换（GB/T 7714）': ('按 GB/T 7714 格式化参考文献',
                            'Format references per GB/T 7714'),
    '两端对齐': ('把文本按两端对齐排版',
           'Justify text to align on both margins'),
    '日历二维码': ('生成可添加到日历的二维码',
             'Create a QR code that adds a calendar event'),
    '广告ROI计算': ('计算广告投放的投入产出比',
              'Compute return on ad spend'),
    '年假计算器': ('按工龄计算可休年假天数',
             'Calculate annual leave days from tenure'),
    '转化（漏斗/流失）分析': ('分析转化漏斗各环节的流失',
                     'Analyze drop-off through a conversion funnel'),
    '黄金纯度（K金与百分比）换算': ('K 金与纯度百分比互算',
                         'Convert gold karat to purity percentage'),
    '景观（风水/视线）分析': ('分析景观视线与风水要点',
                     'Analyze sightlines and feng shui factors'),
    '宾果生成器': ('生成可打印的宾果卡片',
             'Generate printable bingo cards'),
    '21 点模拟器': ('模拟 21 点并给出基本策略提示',
              'Simulate blackjack with basic strategy hints'),
}
